### ISSUE TITLE
Don't mark step definitions as "unused"

### ISSUE THREAD

**Issue by ilanpillemer** [cucumber/cucumber-eclipse#11]
A method that isn't explicitly called from anywhere turns up gray in most IDEs. The exception is JUnit test methods, which the IDE understands are "special" since they are called by reflection by JUnit. Step definitions should be treated the same way.

**Comment by laeubi** [comment]
Can you given an example where a "gray" method appears in Eclipse? I suspect this is using an additional plugin and not using the default eclipse.
