### ISSUE TITLE
Continuous delivery

### ISSUE THREAD

**Issue by daveychu** [cucumber/cucumber-eclipse#111]
I would like to see an automation of (beta) releases so that developers can use the newest features as soon as possible.

**Comment by ilanpillemer** [comment]
Hi,

I agree, If you put in a pull request for this that would be excellent.

Also the current master has a couple of improvements we could release. If
you want to build a next 0.0.x release that would be great too and I would
be happy to merge that in.

I am currently in the middle of a large project in my job that pays my
salary at the moment and am quite busy.

**Comment by daveychu** [comment]
What I mean is an additional update site (called latest or nightly or something like that), that gets the newest build after every commit on the master branch. This update site can be used "at own risk" in that it might contain bugs. Stable releases can still be done in the existing update site, but at least users have the option to use the newest build without having to locally build it themselves.

This kind of automatic releasing would require write-access.

**Comment by qvdk** [comment]
Fixed by #318 

There are now dedicated updates sites for snapshots and releases.
Both are fulfilled automatically. Details on the [wiki](https://github.com/cucumber/cucumber-eclipse/wiki/Automated-builds-and-deployments).
