### ISSUE TITLE
Explain purpose of each project

### ISSUE THREAD

**Issue by daveychu** [cucumber/cucumber-eclipse#113]
cucumber.eclipse.runner does not seem to be contributing anything. What is it for? A general description on the wiki of each project could help contributors in deciding where to place their code.

**Comment by brasmusson** [comment]
The file [CONTRIBUTING.md](https://github.com/cucumber/cucumber-eclipse/blob/master/CONTRIBUTING.md#modules-list) has a short description of each of the plugins.
