### ISSUE TITLE
not able to found file in step definition using . operator

### ISSUE THREAD

**Issue by sharma-rakesh** [cucumber/cucumber-eclipse#118]

**Comment by sharma-rakesh** [comment]
able to find file using absolute path,but not using . operator . how ever same code works with plain java main method . 

cucumber is trying to search my resource files in eclips directory . not in project directory

**Comment by daveychu** [comment]
Can you attach an example?

**Comment by sharma-rakesh** [comment]
File f = new File("./src/values.properties");						
input = new FileInputStream(f);

this value.properties file is being searched in eclipse folder not in  project folder

**Comment by sharma-rakesh** [comment]
File f = new File("./src/values.properties");			
			System.out.println(propertyName  + f.exists());			
			input = new FileInputStream(f);

**Comment by lxbzmy** [comment]
I can confirm this Bug.
The problem is  plugin runner 's working directory is eclipse installation location. not the project directory of feature file.

**Comment by pdincau** [comment]
any news about this issue?

**Comment by lxbzmy** [comment]
@pdincau ，already fixed in master branch. clone and mvn package.

**Comment by pdincau** [comment]
@lxbzmy thanks, can you point out the commit fixing this issue?

**Comment by xpepper** [comment]
Hi @lxbzmy, 
can we close this issue then?

thank you!

**Comment by ilanpillemer** [comment]
Anyone up to cutting a new release as there is quite a lot in master that
is not yet released to the plugin that is available.

**Comment by girijant** [comment]
@lxbzmy,
Closing this issue as per your comment. If you still found issue, please share your comments with proper snapshots/logs.

Thanks,
-Girija
