### ISSUE TITLE
Provide a library for Eclipse API etc. stubbing

### ISSUE THREAD

**Issue by hdpe** [cucumber/cucumber-eclipse#126]
It would be good if we could somehow integrate a mocking library e.g. Mockito into the target platform for test execution, so we could use it for generating stubs (and prevent the probably ill-advised insanity as evidenced by me in 22f8c3a15feade711e7dbda5ea311caa5fa1af65). This would facilitate the testing of classes as units with JUnit in the IDE without having to bring up the whole target platform.

hamcrest-library would be nice too.

**Comment by laeubi** [comment]
Seems to be fixed, please reopen if still an issue
