### ISSUE TITLE
Special characters are lost when Pretty-Format the feature file

### ISSUE THREAD

**Issue by ptimson** [cucumber/cucumber-eclipse#127]
Greek characters and other special chars i.e. Chinese. Are not supported in feature files. When preforming a 'Pretty Format' the characters are changed into question marks '?'

**Comment by laeubi** [comment]
@ptimson Can you provide a sample file?

**Comment by laeubi** [comment]
See https://github.com/cucumber/cucumber-eclipse/issues/442 for further work on this.
