### ISSUE TITLE
How to build and install the plugin from sources

### ISSUE THREAD

**Issue by xpepper** [cucumber/cucumber-eclipse#132]
Hi,
I'd like to build and install the Eclipse plugin starting from the latest sources taken from master.
Can you help me on how to actually do it?

Thanks,

**Comment by slaout** [comment]
Tanks.
Note: there were some "0.0.11" references I had to replace to "0.0.13" and it worked.

I also had a lot of trouble with my corporate settings.xml of Maven (p2 layout was not understood by Maven).
I then created a blank settings.xml with only our corporate proxy, named it settings-for-cucumber-eclipse.xml, and used the following command to run it:
mvn clean install -s settings-for-cucumber-eclipse.xml

If this can be helpful to other people...

With our corporate settings.xml, the error Maven throwed was:
BasicRepositoryConnectorFactory: Cannot access http://download.eclipse.org/releases/indigo with type p2 using the available layout factories:
Maven2RepositoryLayoutFactory: Unsupported repository layout p2
