### ISSUE TITLE
Release 0.0.12

### ISSUE THREAD

**Issue by chanceVermilion** [cucumber/cucumber-eclipse#134]
Issue for doing a release of 0.0.12. Someone with write access will have to create the parent milestone issue.

**Comment by chanceVermilion** [comment]
@ilanpillemer Can you please create the milestone issue so we can do a proper release? I'll gather up the issues fixed in it and do the code changes we need to get the latest on the update site.

**Comment by ilanpillemer** [comment]
I will do that over weekend.
In a crunch in my day job at the moment so will need to wait until then. I
will target Sunday.

**Comment by ilanpillemer** [comment]
Created milestone "Version 0.1.0"
