### ISSUE TITLE
Debugging not working as expected

### ISSUE THREAD

**Issue by connecties** [cucumber/cucumber-eclipse#136]
using Eclipse Kepler SR 2, build id: 20140224-0627,
cucumber plugin: 0.0.11.201406031952
Using Java 7 (SDK: 1.7.0_45_64)

If I right click on my feature file and choose debug, eclipse starts running and executing my feature file. It asks me if I want to switch to debug view. (I click "yes") and it switches the view and stops processing.
What I expect it to do is switch to the file I have put my breakpoint in and highlite the line the breakpoint is on.
The debug thread view is telling me the correct file and line processing is stopped at.
Clicking one of the lines in this view does not do anything. 

If I debug a pure java application I can click these lines and the file view changes to the file mentioned in the line and the specific line is highlited.

Is this  a known issue? ( If so, I did not search well enough. Shame on me)
What to do so it will debug correctly?
Regards.

**Comment by nurb337** [comment]
I had a similar experience. I use JUnit and got debugging to work by creating a new JUnit debug configuration. I set the project name, test class (name of the package and class containing the test runner), and set Test runner to JUnit 4. This works fine - breakpoints are highlighted as I step through the code and I can see which steps are successful in the JUnit output tab.

**Comment by verhagen** [comment]
Here the complete logging as found in the `check.jmx.log`

	2015/10/22 06:57:23 INFO  - jmeter.util.JMeterUtils: Setting Locale to en 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: Loading user properties from: /var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/target/jmeter/bin/user.properties 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: Loading system properties from: /var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/target/jmeter/bin/system.properties 
	2015/10/22 06:57:23 WARN  - jmeter.JMeter: LogLevel: DEBUG 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: Copyright (c) 1998-2015 The Apache Software Foundation 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: Version 2.13 r1665067 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: java.version=1.8.0_60 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: java.vm.name=Java HotSpot(TM) 64-Bit Server VM 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: os.name=Linux 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: os.arch=amd64 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: os.version=3.10.0-229.7.2.el7.x86_64 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: file.encoding=UTF-8 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: Default Locale=English 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: JMeter  Locale=English 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: JMeterHome=/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/target/jmeter 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: user.dir  =/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/target/jmeter/bin 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: PWD       =/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/target/jmeter/bin 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: IP: 172.17.0.1 Name: 4d14addf5da6 FullName: 4d14addf5da6 
	2015/10/22 06:57:23 INFO  - jmeter.services.FileServer: Default base='/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/target/jmeter/bin' 
	2015/10/22 06:57:23 INFO  - jmeter.services.FileServer: Set new base='/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/src/test/jmeter' 
	2015/10/22 06:57:23 INFO  - jmeter.save.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2 
	2015/10/22 06:57:23 INFO  - jmeter.save.SaveService: Using SaveService properties file encoding UTF-8 
	2015/10/22 06:57:23 INFO  - jmeter.save.SaveService: Using SaveService properties file version 1656252 
	2015/10/22 06:57:23 INFO  - jmeter.save.SaveService: Using SaveService properties version 2.8 
	2015/10/22 06:57:23 INFO  - jmeter.save.SaveService: All converter versions present and correct 
	2015/10/22 06:57:23 INFO  - jmeter.save.SaveService: Loading file: /var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/src/test/jmeter/intake_v02.jmx 
	2015/10/22 06:57:23 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Cannot find .className property for htmlParser, using default 
	2015/10/22 06:57:23 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/html is  
	2015/10/22 06:57:23 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xhtml+xml is  
	2015/10/22 06:57:23 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xml is  
	2015/10/22 06:57:23 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/xml is  
	2015/10/22 06:57:23 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser 
	2015/10/22 06:57:24 INFO  - jmeter.JMeter: Creating summariser <summary> 
	2015/10/22 06:57:24 INFO  - jmeter.engine.StandardJMeterEngine: Listeners will be started after enabling running version 
	2015/10/22 06:57:24 INFO  - jmeter.engine.StandardJMeterEngine: To revert to the earlier behaviour, define jmeterengine.startlistenerslater=false 
	2015/10/22 06:57:24 INFO  - jmeter.engine.StandardJMeterEngine: Running the test! 
	2015/10/22 06:57:24 INFO  - jmeter.samplers.SampleEvent: List of sample_variables: [] 
	2015/10/22 06:57:24 INFO  - jmeter.samplers.SampleEvent: List of sample_variables: [] 
	2015/10/22 06:57:24 INFO  - jmeter.engine.util.CompoundVariable: Note: Function class names must contain the string: '.functions.' 
	2015/10/22 06:57:24 INFO  - jmeter.engine.util.CompoundVariable: Note: Function class names must not contain the string: '.gui.' 
	2015/10/22 06:57:24 ERROR - jmeter.JMeter: Uncaught exception:  java.awt.AWTError: Can't connect to X11 window server using ':99' as the value of the DISPLAY variable.
		at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
		at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
		at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
		at java.security.AccessController.doPrivileged(Native Method)
		at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:264)
		at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
		at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
		at java.awt.Window.initGC(Window.java:475)
		at java.awt.Window.init(Window.java:495)
		at java.awt.Window.<init>(Window.java:537)
		at java.awt.Frame.<init>(Frame.java:420)
		at java.awt.Frame.<init>(Frame.java:385)
		at com.ibm.as400.access.ToolboxSignonHandler.displayMessage(ToolboxSignonHandler.java:336)
		at com.ibm.as400.access.ToolboxSignonHandler.displayMessage(ToolboxSignonHandler.java:323)
		at com.ibm.as400.access.ToolboxSignonHandler.userIdDisabled(ToolboxSignonHandler.java:248)
		at com.ibm.as400.access.AS400.promptSignon(AS400.java:2824)
		at com.ibm.as400.access.AS400.signon(AS400.java:4076)
		at com.ibm.as400.access.AS400.connectService(AS400.java:1203)
		at com.ibm.as400.access.AS400JDBCConnection.setProperties(AS400JDBCConnection.java:3342)
		at com.ibm.as400.access.AS400JDBCDriver.prepareConnection(AS400JDBCDriver.java:1419)
		at com.ibm.as400.access.AS400JDBCDriver.initializeConnection(AS400JDBCDriver.java:1256)
		at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:395)
		at java.sql.DriverManager.getConnection(DriverManager.java:664)
		at java.sql.DriverManager.getConnection(DriverManager.java:247)
		at org.apache.avalon.excalibur.datasource.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:142)
		at org.apache.avalon.excalibur.datasource.ResourceLimitingJdbcDataSource.configure(ResourceLimitingJdbcDataSource.java:311)
		at org.apache.jmeter.protocol.jdbc.config.DataSourceElement.initPool(DataSourceElement.java:235)
		at org.apache.jmeter.protocol.jdbc.config.DataSourceElement.testStarted(DataSourceElement.java:108)
		at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:214)
		at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:336)
		at java.lang.Thread.run(Thread.java:745)

	2015/10/22 06:57:24 INFO  - jmeter.reporters.ResultCollector: Shutdown hook started 
	2015/10/22 06:57:24 INFO  - jmeter.reporters.ResultCollector: Shutdown hook ended

**Comment by gibsonm** [comment]
I'm having the same issues.  However, I also get a dialog saying:

"Unable to install breakpoint in .... due to missing line number attributes.  Modify compiler options to generate line number attributes."  Interestingly it has a Guice related part in the error message.  Not sure if that's a red herring.

![image](https://cloud.githubusercontent.com/assets/12829939/11272224/40b032d0-8ec3-11e5-9627-caeb92cbe47e.png)

I've looked at the compiler options, and everything seems to be set correctly (i.e. line number generation has been set)

Has anyone seen this and got a fix?

Thanks

**Comment by ihodges** [comment]
This problem is due to a missing call to 

setDefaultSourceLocator(launch, config); 

in CucumberFeatureLocalApplicationLaunchConfigurationDelegate.

**Comment by Flaburgan** [comment]
@girijant any chance you can have a look at that issue? Is there anything I can do to help?

**Comment by girijant** [comment]
@Flaburgan,
Please share issues in detail with current plugin version, proper use cases, snapshots, error logs(if any) and actual/expected behaviour for better understanding.

Thanks,
-Girija

**Comment by Flaburgan** [comment]
With the very last version (0.21 2nd minor fixes):

*Steps to reproduce:*
- Add a breakpoint to a step definition file
- In the feature file, Right click -> Debug as -> Cucumber feature
- Eclipse switch to the debug perspective 
- The "debug" view is stopped on the breakpoint line

*Expected behavior:*
**Normal eclipse debug behavior:**
- Eclipse switch the current file from the feature file to the step definition file with focus on the breakpoint line
- When "Step Over" button is clicked, the focus go to the next line
- When "Step Into" button is clicked, the focus go into the function, opening the file where the function is defined

*Actual behavior:*
- The feature file is still selected
- Clicking on "Step Over" or "Step Into" correctly execute the code (see "Debug" view) but does not change the line focused.

**Comment by jchoate49** [comment]
I was wondering if this was ever fixed as I have the same problem going on with Cucumber plugin and Eclipse.

**Comment by laeubi** [comment]
Currently the launching does not work very well (see #190) I'm working on fixing this and probably then the debuging will work also.

**Comment by Mina05** [comment]
I'm facing this issue, too. Is there any solution coming for the next time?

**Comment by rive91** [comment]
Found this too, is there any ETA for the fix?

**Comment by DerMozartJBA** [comment]
I can confirm this problem. The issue rises, when directly running a cucumber feature. It is not happening when running via JUnit context. Unfortunately we use one single JUnit-Test to run all our 150 feature files. Therefore it would be much nicer to directly debug a feature.

**Comment by laeubi** [comment]
Debugging will be reworked in 2.x providing an example that fails would help us to verify/develop/improve this feature,

**Comment by laeubi** [comment]
We are currently developing a new version of the cucumber-plugin with improved support for more recent cucumber versions, if you like try out the following update-site (please uninstall the old plugin before):
https://cucumber.github.io/cucumber-eclipse/update-site/main/

There will be no more work on this for v1.x unless someone opens a PR to fix this.
