### ISSUE TITLE
Plugin does not find step definitions that are on classpath dependency

### ISSUE THREAD

**Issue by TuireHolappa** [cucumber/cucumber-eclipse#145]
Thanks a lot for the new feature finding the step definitions with F3.
It seems also to be working with I18n. At least my feature files have the language: fi.

One enhancement would be nice still: 
The doest not find a step definition when using a step from Maven dependency which implementation has been published to the Maven repository. The plugin highlights step definition then as orange.

**Comment by girijant** [comment]
Hi,
I've started working on it...Very soon this feature will be published.

**Comment by cedson** [comment]
I've encountered this need as well - how is it progressing?  :)

**Comment by mareurs** [comment]
What I did as a fix is to add the steps in the project where the feature files are just for references. You will have 2 different mappings to the same regex and should choose the 2nd. It is not pretty but it helps.

**Comment by cedson** [comment]
I can make this work in the fashion you suggest, but then I have to update every run configuration's 'Glue' value to get the Run As... operation to work.  (Each time I work with a new feature file, a new Run Configuration is generated and needs updated)

Clearly not ideal.  :)

**Comment by girijant** [comment]
Hi,
This new feature is completed like : 
- Reading/Reusing Step-Definitions From any External JAR/Maven-Dependency added in class-path :
• Bundle any cucumber java project OR Build any cucumber maven project having Features/Step-Definitions.
• Create new java/maven project, above JAR must be added into your new project class-path OR Add the above maven-module as maven-dependency into pom.xml file of your new maven-project.
• Feature is Enabled through the 'Preference Page'-> 'Cucumber User Settings', User MUST  have to configure the root package name (ex. com.motive.bdd.hdm) contains all Step-Definitions as a bundled project.
• All External Step-Definitions list can be auto populated into your new feature file through 'Content Assistance' feature and can be reused into your current project.

This feature is almost completed, some part of testing is pending.

**Comment by lucasgut** [comment]
@girijant this is just what I need, any idea when this will be available?

**Comment by girijant** [comment]
@lucasgut Now I'm fixing some issues found after testing this feature. Once it's done I'll send a pull request   asap.

**Comment by girijant** [comment]
@lucasgut I've Implemented this new feature with new version '0.0.16.201703160952' and also requested for new pull requests. Once it's done, you can consume. Please refer the wiki page [Reusing Of Step Definitions From External Class Path Dependencies(JAR POM...etc)](https://github.com/cucumber/cucumber-eclipse/wiki/Reusing-Of-Step-Definitions-From-External-Class-Path-Dependencies(JAR-POM...etc)) for the reference.

**Comment by lucasgut** [comment]
Great thanks, much appreciated! Looking forward to try it out.

**Comment by girijant** [comment]
@ilanpillemer Please close this ticket.

**Comment by simonezampinistud** [comment]
Could you please help me with latest version of the plugin?
Right now I can execute tests (Eclipse JUnit or Maven, both works), I can see all steps in white, Cucumber assistance (CTRL+space) works 100% but "Find step definition (F3)" (CRTL+mouse left button) works only for steps declared in the project.
