### ISSUE TITLE
News posts not formatted well

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-eclipse#167]
I noticed today that the plugin site was looking a bit rough, caused I think by our move from the cukes.info site over to cucumber.io.

I tidied up the stylesheet links and a missing logo, but I also noticed that the news feed posts are broken - there are no newlines in the posts:

![screen shot 2016-06-22 at 12 11 06](https://cloud.githubusercontent.com/assets/19260/16274177/6f605a34-3872-11e6-9406-b0ac7bf681a1.png)

I've run out of time to fix it, hence this issue :)

**Comment by laeubi** [comment]
Seems everyone else also runs out of time, please reopen if you plan to further work on this.
