### ISSUE TITLE
Http:Proxy Authentication required  for cucumber eclipse plugin installation in eclipse

### ISSUE THREAD

**Issue by aviju2007** [cucumber/cucumber-eclipse#170]
Dear All,

I am writing a BDD framework using Selenium Java and cucumber.As a part our installation, I have downloaded and installed Java SDk8U91,Eclipse Neon for 64 bit Version: Neon Release (4.6.0).Then I tried to install cucumber eclipse  plugin from eclipse help->install new software.There I add the repository , name :Cucumber and location:http://cucumber.github.com/cucumber-eclipse/update-site
and click .But it is showing an error as ,mentioned 

"HTTP Proxy Authentication Required: http://cucumber.github.com/cucumber-eclipse/update-site/content.xml
HTTP Proxy Authentication Required: http://cucumber.github.com/cucumber-eclipse/update-site/content.xml
Proxy Authentication Required"

tried with setting proxy in IE and as well as in Eclipse -> preferences ->General ->Network Connections. and select as MANUAL with http,https and socks as checked with host,port,user and pwd defined for our network(Checked network team to get authetication userid and pwd for my VM)
This entire setup in a VM (remote desktop)

Even after that problem does not resolve.Search lots of forum but it does not solve my purpose.
Can anybody please help me in this regard.

Regards,
Avijit Dutta

**Comment by girijant** [comment]
See : http://stackoverflow.com/questions/1940984/how-to-specify-eclipse-proxy-authentication-credentials

**Comment by girijant** [comment]
Closing this ticket as non-reproducible defect.
