### ISSUE TITLE
Scenario Outline step is not recognized when using alternatives

### ISSUE THREAD

**Issue by jorisweges** [cucumber/cucumber-eclipse#182]
I have a step definition that uses an alternative capturing group "(does|does not)". This step definition IS recognized when used in a regular scenario (!). If I use it inside an Scenario Outline, I get the "does not have a matching glue code" warning. When I run Cucumber, then the step is recognized and the scenario outline passes. If I change the definition to use a wildcard "(.*)", the warning is no longer shown (and the test still passes).

**Comment by qvdk** [comment]
Resolved in #305 

![screenshot from 2018-12-30 02-46-37](https://user-images.githubusercontent.com/6142398/50543604-454f1780-0bdd-11e9-9a19-fbe1243ca84d.png)
