### ISSUE TITLE
How do i install this?

### ISSUE THREAD

**Issue by bharal** [cucumber/cucumber-eclipse#187]
The github links to the web site for installation instructions.

The website readme links to github.

Someone done messed up, please put something so that people like me can just install your plugin and get on with life?

**Comment by johny2000uwb** [comment]
I cannot... the eclipse update site does not work....

**Comment by johny2000uwb** [comment]
URL is wrong..
http://cucumber.github.io/cucumber-eclipse/update-site/ 
these is correct

**Comment by girijant** [comment]
@bharal,
Glad to publish Cucumber-Eclipse plugin as a Zip file which can be downloaded and installed from your local system.
You can directly install this plugin from our [Updated Site](https://cucumber.io/cucumber-eclipse/update-site)

You may refer our [Eclipse-Marketplace URL](https://marketplace.eclipse.org/content/cucumber-eclipse-plugin) for quick installation from Eclipse

You may download the plugin-zip(cucumber-eclipse-plugin-0.0.19-SNAPSHOT.zip) from the latest version(0.0.19-SNAPSHOT) directory of below url:
- https://github.com/cucumber/cucumber-eclipse/tree/master/cucumber.eclipse.download/download

Also refer our [Plugin-Download/Installation-Wiki](https://github.com/cucumber/cucumber-eclipse/wiki/Eclipse-Market-Place-For-Cucumber-Eclipse-Plugin) for detail information

Hence closing this ticket.
