### ISSUE TITLE
Step Def Wizard: Path separator fails on windows when the file browser is used

### ISSUE THREAD

**Issue by csmoseley** [cucumber/cucumber-eclipse#196]
I'm looking at this, because it appears my newest change inverted a different bug.

Before 0.0.17, the pre-populated path was failing to generate correctly, but now it generates correctly and the file selector is broken.

I'm reading up on the problem and wondering if its something to do with how we are prepopulating the path.

I'm also looking into using a path independent file seperator, but I don't think that will fix everything.

**Comment by csmoseley** [comment]
This was revealed by the change I made in #192 to fix pre-populated path being incorrect

**Comment by girijant** [comment]
Closing this ticket as already fixed.
