### ISSUE TITLE
Class not found exception

### ISSUE THREAD

**Issue by sanjay1984** [cucumber/cucumber-eclipse#198]
Hi All,

I am getting class not found exception every time when I am running my RunTest,java class, can anyone please check what is the issue, I think some problem with the @CucumberOptions

![cucumber](https://cloud.githubusercontent.com/assets/26081637/26031968/07af5f48-388f-11e7-9098-ebb0acc8ed64.PNG)

I tried so many workarounds but no luck.

Regards,
Sanjay

**Comment by girijant** [comment]
Hi Sanjay,
Please try with **"@CucumberOptions(features="feature/Boutiqaat.feature", glue={"src/test/java/cucumber.steps"})"**

Thanks,
-Girija

**Comment by sanjay1984** [comment]
Thanks, Girija.

I think you are suggesting to put double quotes before the cumberoptions and end of this line.
If you are referring this, I tried but again error is coming syntax error with tokens, delete the tokens.

Regards,
Sanjay

**Comment by girijant** [comment]
Sanjay,
I updated my comment.From your attached snap-shot, it seems your maven-project(i.e. boutiqaat.automation.test) having error(Red mark). Please properly correct your maven project without any error and retry.

Thanks,
-Girija

**Comment by sanjay1984** [comment]
Ok, let me try to fix that first.

Regards,
Sanjay

**Comment by sanjay1984** [comment]
@girijant I fixed that red mark issue.

The test which I am trying to run is basically appium (android app) automation, I created one class with all capabilities and I am creating the object of this class in step definition class (which consists of all the steps), When I am running, I am able to open the android app on my real device but further actions are not executing as per my script.

I am getting java.lang.NullPointerException. Please find attached my step definition class code.

![step defination](https://cloud.githubusercontent.com/assets/26081637/26033088/09fb9510-38ac-11e7-8cf5-9270a3583caa.PNG)

Please let me know what wrong I am doing.

Regards,
Sanjay

**Comment by girijant** [comment]
@sanjay1984 Your above script is buggy itself instead of Cucumber plugin i.e. WebDriver object is null (WebDriver driver = null) and causing java.lang.nullPointerException. So intialize it properly. I would suggest use WebDriver PageObjectModel and invoke those methods on cucumber Step-Definition files.  

Thanks,
-Girija

**Comment by girijant** [comment]
Closing this ticket as a non-reproducible defect.

**Comment by raj2k0072000** [comment]
I am having the same issue. When I run it as Cucumber it works fine but when I run it as a Junit Runner Class it fails. Class Not Found and it is not able to find the Runner Class.

**Comment by girijant** [comment]
@raj2k0072000 , @sanjay1984,
This issue is non-reproducible in our environment. It seems some configuration issue in your setup. Please try with below setup, it may work :
**a. Add below Cucumber-JVM-Junit JAR into your class-path or maven-dependency:**
`https://mvnrepository.com/artifact/io.cucumber/cucumber-junit`
**b. Import as below in your Runner class:**
```
import org.junit.runner.RunWith;
import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
```
**c. Update Runner class with below cucumber options:**
 ```
@RunWith(Cucumber.class)
AND
@CucumberOptions(features="feature", glue={"cucumber/steps"})
OR
@CucumberOptions(features="feature/Boutiqaat.feature", glue={"cucumber/steps"})
OR
@CucumberOptions(features="feature/Boutiqaat.feature", glue={"classpath:src/test/java/cucumber/steps"})
```

**Comment by SaptakBagchi** [comment]
**I am getting the same error:**


**Runner:**

package runner;



import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;

@RunWith(Cucumber.class)
@CucumberOptions(
		features = "features",
		glue = {"classpath:/com.MavenCucumber.cucumber/src/test/java/stepDefination"}
		)
public class TestRunner {

}


Error: 

class not found in the selected project


The same code is working properly with cucumber jars but behaving like this with maven repository

**Comment by vandanagaikwad3** [comment]
import org.junit.runner.RunWith;
import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
//import cucumber.api.testng.AbstractTestNGCucumberTests;

@RunWith(Cucumber.class)
@CucumberOptions(
		features="src/test/java/Feature",
		glue= {"StepDefination"}
		)


public class TestRunner {

}

**Comment by vandanagaikwad3** [comment]
Not working using maven

**Comment by blueskysagar** [comment]
I tried everything but I am having same problem. My test runner class is not found what to do?
