### ISSUE TITLE
Can't download Cucumber Eclipse Plugin. 

### ISSUE THREAD

**Issue by asytnik** [cucumber/cucumber-eclipse#209]
Response - Some information not is found.

**Comment by ironchamp** [comment]
How can I download offline?

**Comment by girijant** [comment]
@asytnik , @ironchamp,
Currently I am working to publish our cucumber-eclipse plugin for offline-installation. You will be notified once it's completed.

Thanks,
-Girija

**Comment by girijant** [comment]
@asytnik , @ironchamp,
Glad to publish Cucumber-Eclipse plugin as a Zip file which can be downloaded and installed from your local system.

Please download the plugin-zip(cucumber-eclipse-plugin-0.0.19-SNAPSHOT.zip) from the latest version(0.0.19-SNAPSHOT) directory of below url:
- https://github.com/cucumber/cucumber-eclipse/tree/master/cucumber.eclipse.download/download

Also refer our [Plugin-Download/Installation-Wiki](https://github.com/cucumber/cucumber-eclipse/wiki/Download-and-Install-Plugin-From-Zip) for detail information

Hence closing this ticket.
