### ISSUE TITLE
Content assist does not populate steps that are defined using java 8 lambda expressions

### ISSUE THREAD

**Issue by akshaykamath** [cucumber/cucumber-eclipse#223]
This is probably related to #207 . The step definitions that are defined in java class file using the lambda expressions are not displayed in the content assist.

![scrshotstepdef-java8-classfile](https://user-images.githubusercontent.com/13991499/33298540-931cdcfa-d3ac-11e7-9e2d-b1c452299a93.png)
![scrshotstepdef-java8](https://user-images.githubusercontent.com/13991499/33298544-96aae0ce-d3ac-11e7-8c1e-c96d57e3ad2a.png)

**Comment by girijant** [comment]
@akshaykamath,
Above issues for java8 environment is almost completed. Currently doing some testing. I will fire a build once its done.

**Comment by girijant** [comment]
@akshaykamath,
Glad to announce the new release(0.0.20 version) of Cucumber-Eclipse plugin which supports cucumber-java8 Lambda Expressions. The Plugin is enhanced to support below features for cucumber-java8 Lambda Expressions :
- Content-Assistance populates all the steps used in lambda expressions.
- Matching of Glue-code for all the steps used in lambda expressions.
- By pressing 'F3' key on steps in feature file navigates to the corresponding lambda-expression steps. 

Please refer our wiki page of [Lambda Expression support for Cucumber-Java8](https://github.com/cucumber/cucumber-eclipse/wiki/Lambda-Expression-support-for-Cucumber-Java8) for detail information.
Please update the plugin with the latest '0.0.20' version and let me know if you face any issue. Also I am closing this ticket.

Happy BDD-Automation !!!

Thanks,
-Girija
