### ISSUE TITLE
0.0.20 version triggers a null pointer exception when editing a feature file

### ISSUE THREAD

**Issue by mikejramsey56** [cucumber/cucumber-eclipse#229]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=529209

I ran into this after an Eclipse update. After the update I had this installed:

Cucumber Eclipse Feature 0.0.20.201712221009 cucumber.eclipse.feature.feature.group

I uninstalled the 0.0.20 version. I then went to the git site 
https://github.com/cucumber/cucumber-eclipse/tree/master/cucumber.eclipse.download/download

and downloaded the previous version, 0.0.19. 

I followed the install directions and after the restart, the editor was working again.

Here is my installed software after regressing to 0.0.19:
[platform details.txt](https://github.com/cucumber/cucumber-eclipse/files/1604772/platform.details.txt)

**Comment by girijant** [comment]
@mikejramsey56, 
Thanks for identifying issue. 
Please share exception stack trace with snapshots for quick debugging. Also share your both feature file and step definitions file along with eclipse platform detail.

**Comment by girijant** [comment]
@mikejramsey56,
After successfully installing latest Cucumber-Eclipse plugin version:**0.0.20**(Cucumber Eclipse Feature 0.0.20.201712221009 cucumber.eclipse.feature.feature.group) with a fresh **Eclipse-Oxygen** IDE [Eclipse Java EE IDE for Web Developers, Version: Oxygen.2 Release (4.7.2), Build id: 20171218-0600], the cucumber feature file(.feature) is successfully launched in eclipse editor **without throwing any exception stack**.

Please find below snapshots for your reference.

![eclipse-oxygen_test](https://user-images.githubusercontent.com/17194046/34641387-81c211fe-f329-11e7-89d9-e03573cf02c5.jpg)

It seems some issue with your eclipse environment. Points needs to be considered while installing new cucumber-eclipse plugin:
- After installing plugin, eclipse-ide must be restared.
- Older plugin version needs to be properly removed/uninstalled from your eclipse, please refer this : https://github.com/cucumber/cucumber-eclipse/wiki/Uninstall-the-older-version-of-cucumber-eclipse-plugin

Hence I'm closing this ticket. If you have any concern, please reopen with your comments.
