### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by testronic** [cucumber/cucumber-eclipse#231]
In my opinion the old icon looks much better 
![image](https://user-images.githubusercontent.com/34661453/34794064-4a680a7a-f602-11e7-9e9b-adff8d2ae29b.png)
than new 
![image](https://user-images.githubusercontent.com/34661453/34794177-b35f9d5e-f602-11e7-86ac-77ec6843cdae.png)
The selected color is too dark and and aggressive...
It looks terrible on the dark color theme... 
![image](https://user-images.githubusercontent.com/34661453/34794432-7880bbea-f603-11e7-8d40-61306ae0c61e.png)

**Comment by girijant** [comment]
@testronic,
As old icon ![](https://user-images.githubusercontent.com/34661453/34794064-4a680a7a-f602-11e7-9e9b-adff8d2ae29b.png) was not identical with the cucumber-logo, making confusion for new user. The new icon ![](https://user-images.githubusercontent.com/34661453/34794177-b35f9d5e-f602-11e7-86ac-77ec6843cdae.png) is replaced for better understanding purpose. The selected color is the default color of cucumber-logo and looks perfect with eclipse default color theme. As per your suggestion the new icon color can be changed on next release unwards.

**Comment by aslakhellesoy** [comment]
Thanks for changing this! We shouldn’t be using the old logo on any Cucumber projects, so this is good.

More info here: https://github.com/cucumber-ltd/brand

**Comment by aslakhellesoy** [comment]
In that repo there are white logos with green pips that could be used on dark schemes. I don’t know if Eclipse is able to swap icons based on the “darkness” of the current theme though.

**Comment by girijant** [comment]
@aslakhellesoy ,
Thanks for your valuable comments and sharing the repo of all logo/icon. Let me look into the swapping of icons based on eclipse color theme.

**Comment by testronic** [comment]
Guys all you say is right, but you slightly misread my initial comment. Ok. I'll try to help you...
My concern is not the shape of the icon, but the selected color, which is too dark even if you compare it with the original logo. Please take a look...
<img width="187" alt="screen shot 2018-01-13 at 2 11 25 pm" src="https://user-images.githubusercontent.com/34661453/34910836-0b9f8404-f872-11e7-8828-e06e42108393.png">
<img width="102" alt="screen shot 2018-01-13 at 1 59 55 pm" src="https://user-images.githubusercontent.com/34661453/34910837-10443e82-f872-11e7-9ccf-c4269033a9f9.png">
I hope now you can see the difference...
Even on this page, where you are reading this comment, take a look at the green button. Try to compare it with colors on this site: https://cucumber.io They are identical because it's a standard.

**Comment by lshiv080374** [comment]
hi, can someone guide... for me the cucumber icon looks very faded - in light green... is there a problem with installation? am new to cucumber-eclipse
![cucumber icon](https://user-images.githubusercontent.com/15176261/36854145-3afb32a2-1d3e-11e8-95b8-7c96468f264d.JPG)

**Comment by girijant** [comment]
@lshiv080374,
Those above cucumber icons are not our plugin icons. You might installed different plugin. Please uninstall that plugin and install our plugin from eclipse marketplace. You will get proper icon.

Thanks, 
Girija

**Comment by aslakhellesoy** [comment]
@lshiv080374 my guess would be that it's the unofficial agileware plugin that has those faded non-standard cucumber icons.

Did you try uninstalling it?

**Comment by lshiv080374** [comment]
yes i uninstalled both of them and installed them from market place... still the same

**Comment by aslakhellesoy** [comment]
@lshiv080374 uninstall the unofficial `org.agileware` one so you only have the official `cucumber.eclipse` one.

Any better?

**Comment by lshiv080374** [comment]
not yet... when i removed that, i got this No editor descriptor for id org.agileware.natural.cucumber.Cucumber when i tried to open a feature file....and the icon is completely gone, replaced by a small square red icon...am in the process of comparing my set of installed plugins with what my colleague has, install the ones i don't have and come back to this forum...may be with a positive news... thank you for pitching and helping

**Comment by girijant** [comment]
@lshiv080374,
Please retry with below steps :

**A. Uninstall both Plugin-Features From Eclipse:**
- Open Eclipse-IDE, Close all feature files opened in editor.
- Click **Help** > **About Eclipse** > **Installation Details**, 
- Select both **'Cucumber Eclipse Feature(cucumber.eclipse)'** and **'org.agileware'**
- Click Delete

**B. Manually remove both Plugins and Features from Eclipse:**
As there is no mechanism within Eclipse to permanently and physically uninstall a feature and its plug-ins, you will have to manually remove the files associated with the cucumber-eclipse features and plugin when Eclipse is not running as per below:

> Warning Note: Be very cautious as to which files you delete, and always have a backup of your Eclipse directory. If you remove the wrong files from these directories, you may have quite some trouble restoring your Eclipse to a stable state. Therefore, unless your hard disk storage capacity is extraordinarily limited, it is recommended that you simply leave the physical files in place.

- From your eclipse-installed dir, go to **eclipse/features** directory: 
-- Delete if any existing cucumber-eclipse feature directory named as **cucumber.eclipse.feature_**.
-- Delete if any 'org.agileware' feature available.
- From your eclipse-installed dir, go to **eclipse/plugins** directory:
-- Delete the cucumber-eclipse plug-in jars named as: 
-- cucumber.eclipse.editor_.jar, 
-- cucumber.eclipse.steps.integration_.jar, 
-- cucumber.eclipse.steps.jdt_.jar
-- Also delete JARs named with 'org.agileware'
- Now restart Eclipse again and remove the existing cucumber-eclipse plugin site url: 
-- Run Window > Preferences > Install/Update > Available Software Sites, 
--  Select name/location of Cucumber-Plugin and 'org.agileware' 
-- Click Remove, Click Ok.
- Now Restart your eclipse.

**C. Clear Eclipse-Cache :**
Clear your eclipse cache with below steps:
- Open Eclipse and navigate to the Window > Preferences.
- Scroll down the left-hand panel in the Preferences window and click the Remote Systems drop-down root menu. Select File Cache.
- Click the Clear Cached Files button in the File Cache window. Note that this will automatically close any open remote files on your computer.
- Press Apply and OK to save your changes and exit out of the Preferences window.
- Restart Eclipse

Please retry with above steps and let me know.

Thanks,
-Girija

**Comment by lshiv080374** [comment]
Hi Girijant,
I tried doing all these... but in vain... so googled further, found this: https://github.com/cucumber/cucumber-eclipse/wiki/Eclipse-Market-For-Cucumber-Eclipse-Plugin - following this, i uninstalled the cucumber and natural plugins, opened artifacts.xml, removed all references to cucumber, saved it, opened eclipse once again, installed cucumber plugin, and boom, i got the icon i was looking for and eclipse is not asking me to install natural... looks like my installation is good... though technically i did not understand what i did... 
thank you so much for being patient and supportive! 
Warm regards,
Lavanya Shivram

**Comment by lshiv080374** [comment]
![icons](https://user-images.githubusercontent.com/15176261/37057014-07f7bc94-2154-11e8-8401-64a2a6cebedb.JPG)

**Comment by girijant** [comment]
@lshiv080374,
Thanks. As I told before, it was eclipse cache issue. Anyway you can continue your cucumber automation.

**Comment by girijant** [comment]
Closing this ticket as per above solution.

**Comment by swethayellanuru** [comment]
> Hi Girijant,
> I tried doing all these... but in vain... so googled further, found this: https://github.com/cucumber/cucumber-eclipse/wiki/Eclipse-Market-For-Cucumber-Eclipse-Plugin - following this, i uninstalled the cucumber and natural plugins, opened artifacts.xml, removed all references to cucumber, saved it, opened eclipse once again, installed cucumber plugin, and boom, i got the icon i was looking for and eclipse is not asking me to install natural... looks like my installation is good... though technically i did not understand what i did...
> thank you so much for being patient and supportive!
> Warm regards,
> Lavanya Shivram



> Hi Girijant,
> I tried doing all these... but in vain... so googled further, found this: https://github.com/cucumber/cucumber-eclipse/wiki/Eclipse-Market-For-Cucumber-Eclipse-Plugin - following this, i uninstalled the cucumber and natural plugins, opened artifacts.xml, removed all references to cucumber, saved it, opened eclipse once again, installed cucumber plugin, and boom, i got the icon i was looking for and eclipse is not asking me to install natural... looks like my installation is good... though technically i did not understand what i did...
> thank you so much for being patient and supportive!
> Warm regards,
> Lavanya Shivram

Hi Lavanya,

I couldn't find anything here: https://github.com/cucumber/cucumber-eclipse/wiki/Eclipse-Market-For-Cucumber-Eclipse-Plugin . Could you please share the right link if possible. I appreciate your help.

Thanks
Swetha
