### ISSUE TITLE
Feature file error highlighting options

### ISSUE THREAD

**Issue by testronic** [cucumber/cucumber-eclipse#233]
I'm struggling with error highlighting in the feature file. 
1. Is there an option to change the default color or method ? (e.g. underline instead of highlighting)
-Dark theme-
![image](https://user-images.githubusercontent.com/34661453/35065810-3d8fc226-fb83-11e7-9e16-d48287a2495e.png)
-Windows (default) theme-
![image](https://user-images.githubusercontent.com/34661453/35065885-8161c60c-fb83-11e7-8b36-46aabf6432b2.png)

2. Error is displayed even after a corresponding method has been created in a step implementation class. The refresh option does not help. The only work around is to close then open the affected feature file. Am I missing something or this is an expected behavior?

**Comment by Flaburgan** [comment]
>Error is displayed even after a corresponding method has been created in a step implementation class. The refresh option does not help. The only work around is to close then open the affected feature file. Am I missing something or this is an expected behavior?

+1 on this, I have the same problem. I don't think this is the expected behavior, the file should be re-checked automatically.

**Comment by futrethegreat** [comment]
I am having same strange behaviour. Every time I change anything in the feature file, a warning is displayed even though syntax is correct; I have to close file and open again to have warnings off. Is a solution to this feasible soon?

**Comment by arslantx** [comment]
I found the solution for changing the highlighting color.
Window >> Preferences >> General >> Editors >> Text Editors >> Annotations >> Unmatched step error. Change the Text as Highlighted color from here to different color.
But can't speak about 2nd problem as mine automatically updates once matching step is defined.

**Comment by qvdk** [comment]
I can reproduce the second problem.
The plugin should reload step definitions on save, but the builder `cucumber.eclipse.steps.jdt.StepsBuilder`  is not executed.

I do not know why for the moment. The extension seems to be properly configured.
