### ISSUE TITLE
Steps detected as not implemented when they contains a number (\\d+) regexp

### ISSUE THREAD

**Issue by Flaburgan** [cucumber/cucumber-eclipse#235]
I've got a step wrote as `And there should be 2 passengers`.
And implemented as `And("^there should be (\\d+) passengers$", (Integer nbPassengers) -> {`

The eclipse plugin 0.0.20.201712221009 is unable to link that step to the glue code and displays a warning in the feature file. However, I'm able to run my scenario without problem.

**Comment by girijant** [comment]
Thanks for sharing issue. I will look into this. Also waiting for any other issues in java8 - lambda expression, so that I could fix all in a single release build.

**Comment by girijant** [comment]
@Flaburgan,
Issue got fixed in 0.0.21-SNAPSHOT, Please retry by updating your existing plugin. So closing this ticket.
