### ISSUE TITLE
Missing artifact errors in pom.xml

### ISSUE THREAD

**Issue by alice-0-kim** [cucumber/cucumber-eclipse#249]
Hi,

I am trying to create a new Maven project in Eclipse environment but couldn't build the project because of the errors arose while in the process. I suspect that it is to do with downloading cucumber-eclipse plugin, and I have the zip folder (cucumber-eclipse-plugin-0.0.21-SNAPSHOT) downloaded and unzipped in my local environment. I was wondering if it is the right folder to download and how I could let Eclipse aware of such folder.

Any help would be appreciated. Thank you.

![screen shot 2018-02-21 at 10 51 26 am](https://user-images.githubusercontent.com/28884850/36499139-3008e3a2-16f5-11e8-9970-ac8ad37bce10.png)

**Comment by girijant** [comment]
@alice-0-kim,
You have to install the downloaded cucumber-eclipse plugin(0.0.21 snapshot) zip in your eclipse as an archive. The error you are seeing in your pom.xml is due to configuration issue of your maven-settings. xml file instead of our plugin issue.

Thanks, 
Girija
