### ISSUE TITLE
How to call an external method in cucumber framework from test runner after the cucumber.json file is generated

### ISSUE THREAD

**Issue by abhilashmt** [cucumber/cucumber-eclipse#253]
I have created a custom report in cucumber using the cucumber json file creating after the execution of a test. How can i call the custom method function from my cucumber test runner after the json file got created.
I tried with @AfterClass but the json file is creating after this method only.

**Comment by laeubi** [comment]
Please use one of the support channel http://cucumber.io/support#slack instead of the issue tracker to ask questions.
