### ISSUE TITLE
PHP - Behat support?

### ISSUE THREAD

**Issue by smtlab** [cucumber/cucumber-eclipse#254]
Does cucumber-eclipse support Behat for PHP Developers?
Or is there a way we can make it work for eclipse PDT which support similar features offered for Java.
ex: Reusing Step-Definitions From Class-Path Dependency

**Comment by girijant** [comment]
@smtlab,
As of now this plugin doesn't support Behat for PHP Developer. Currently this plugin is only focusing on Gherkin-Java in eclipse-platform by using eclipse JDT. So you may concern to our admin for the separate project/trunk i.e. cucumber-eclipse-php. 

Thanks,
-Girija

**Comment by girijant** [comment]
Closing this ticket
