### ISSUE TITLE
Bad link in readme.md instructions

### ISSUE THREAD

**Issue by mikepotter1024** [cucumber/cucumber-eclipse#260]
On the Code tab in the readme.md the 2nd bullet item the skeleton link doesnt exist gets a 404.

"After you install the Cucumber-Eclipse plugin, you can use it to run Cucumber-JVM. To do this, you will need to install all the libraries you want to use for Cucumber-JVM into your Eclipse project's build-path libraries. The likely candidates and their locations are in the download target at the **cucumber-java-skeleton** example at GitHub."

**Comment by akshaykamath** [comment]
This  issue is resolved.
