### ISSUE TITLE
Features and step definitions are glued and working, but Eclipse shows warning for no step definition

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-eclipse#263]
_From @osuser2018 on May 31, 2018 14:12_

All of my features and step definitions are working just fine.  But, in each feature, most if not all of the steps show a yellow underline warning with a message similar to this:  "No definition found for 'I log into the system'".  I'd like to get rid of this warning line as it confuses new developers coming onto the project.

What is crazy is that some steps do not show this error but they reside in the exact same step definition file as the ones that do show the error.  

I am not using regular expressions.  I do however pass parameters into a couple of steps, but probably 99% are just basic English phrases like "I log out of the system."

In my runner, I have the following CucumberOptions:
```
@CucumberOptions(
		features = {"classpath:test/features/facility"},
		glue = {"classpath:test/java/stepDefinitions/facility",
				"classpath:test/java/stepDefinitions/shared",
				"classpath:test/java/stepDefinitions/background"},
		plugin = {
				"progress",
				"json:target/cucumberFacility.json"
				},
		strict = false,
		dryRun = false,
		monochrome = true,
		tags = {"@Facility_Manage"}
				)
```

I am using Eclipse Oxygen (March 2018), 
Cucumber Eclipse Feature v. 0.0.21.201802160922	cucumber.eclipse.feature.feature.group	
Cucumber Editor	v. 0.7.6.201505100000	org.agileware.natural.cucumber.feature.feature.group	

_Copied from original issue: cucumber/cucumber-jvm#1378_

**Comment by osuser2018** [comment]
I see no comment on the issue I logged here.   Did you mean to leave a comment or are you ignoring/deleting my issue?

**Comment by johny2000uwb** [comment]
Be patient. Issue has been moved to correct Project. Could you provide a screenshot?

**Comment by osuser2018** [comment]
Gotcha.  Here's a screenshot of one of my features where you can see some showing the warning and some that do not...

![image](https://user-images.githubusercontent.com/39202294/40792280-9656a818-64c7-11e8-8aab-ee6b98862d4f.png)

Again, all of these steps map correctly to their matching step definition file.

Thanks!

**Comment by johny2000uwb** [comment]
But this is not our plugin? This is Natural editor? Correct?

**Comment by johny2000uwb** [comment]
Natural Plugin is not a part of this project. Please report the problem direct to Natural Plugin.

**Comment by osuser2018** [comment]
I believe I fixed the issue by adding the specific location of the feature files and the specific location of the step definitions to the build path.  Previously, I had the only the folders one level up in the build path.  In other words, I had "test/java" only and now I have added "test/java/stepDefinitions".  I also added my features folder as well into the path (i.e., "test/features").
