### ISSUE TITLE
Issue in Photon Release Candidate 2 (4.8.0RC2)  with cucuumber version 0.0.21.201802160922

### ISSUE THREAD

**Issue by Ganeshankarthik** [cucumber/cucumber-eclipse#266]
Hi ,

when i create a new Maven project i am able to open the feature files but if i add my dependencies the same feature file throws error as "Editor could not be initialized".

Below are the screenshot of my projects and attached my POM.xml if any compilation issue.

![screenshot1](https://user-images.githubusercontent.com/24904232/41159817-60a1aeae-6b4b-11e8-8516-4c14635d0f3c.PNG)
![screenshot2](https://user-images.githubusercontent.com/24904232/41159818-60d82f74-6b4b-11e8-8a10-dbcfa7218d6e.PNG)

![pomxml1](https://user-images.githubusercontent.com/24904232/41159924-c3ab1198-6b4b-11e8-8d1a-5870e2a074ec.PNG)
![pomxml2](https://user-images.githubusercontent.com/24904232/41159926-c3e6fd48-6b4b-11e8-925a-55dda4e0854b.PNG)
![pomxml3](https://user-images.githubusercontent.com/24904232/41159928-c41b8464-6b4b-11e8-933d-95d2f3cd85de.PNG)

**Comment by Ganeshankarthik** [comment]
Adding the below issue also when saving the feature 
An error has occurred. See error log for more details.
Unexpected internal error near index 45
^Changes made to the User Id should be saved\
![internalerror](https://user-images.githubusercontent.com/24904232/41161850-c00a0110-6b51-11e8-95bc-0360f802b53c.PNG)

**Comment by qvdk** [comment]
Could you provide a sample project for which the issue occurs please ?

**Comment by girijant** [comment]
Closing this ticekt.
