### ISSUE TITLE
Eclipse- Oxygen 3 A (Oxygen.3a Release (4.7.3a))is not supporting cucumber

### ISSUE THREAD

**Issue by vishy-maverick** [cucumber/cucumber-eclipse#270]
I have installed cucumber . infact all feature files appear in the cucumber feature file format

but GIVEN,WHEN,THEN  whole statements are appearing in Red texts and when i press F3 by selecting any of the GIVEN.WHEN, THEN statements , it's not navigating to respective step definition files.

**Comment by PyvesB** [comment]
Hello @vishy-maverick ,

Shouldn't the keywords be in capitalised lower case? For instance "Given", "When", "Then", etc., as specified in the [documentation](https://docs.cucumber.io/gherkin/reference/#keywords).

Cheers,

Pyves

**Comment by girijant** [comment]
closing this ticket.
