### ISSUE TITLE
Feature Request - add JavaDoc to step

### ISSUE THREAD

**Issue by davidgenrich** [cucumber/cucumber-eclipse#271]
![step_javadoc_example](https://user-images.githubusercontent.com/5230597/41781841-5bb6f24e-75ed-11e8-818f-c9e090e0b7af.jpg)
Didn't find anyplace to send a feature request, so adding this as a issue.

I see that you know show the Step, Source File, and Line number where a Step is defined.  That is great.

Would love to see a feature were the JavaDoc for the Step is also shown.  That would make Cucumber and this plugin even more useful and powerful.  I haven't found a plug that does that, but since your now able to show the source location, should be easy to add in the JavaDoc.

A mock up is attached.,

**Comment by girijant** [comment]
@davidgenrich,
Thanks for the new request. We are considering this as a new feature.

Thanks,
-Girija

**Comment by johny2000uwb** [comment]
Javadoc for Gherkin Steps? I though, that the goal of this approach ist to have a step so written, that i do not need some other documentation.

**Comment by davidgenrich** [comment]
When you have 1000’s of steps (high level steps, not low level steps), spanning multiple applications that all interconnect, knowing what step does what is helpful.  But I do see your point.

**Comment by laeubi** [comment]
This is supported in the 2.x line now
