### ISSUE TITLE
Error - Artifact not found - 0.0.22.201806032001.jar

### ISSUE THREAD

**Issue by punarjit-singh** [cucumber/cucumber-eclipse#272]
Hi @there

I am not able to install this plugin on the following eclipse version:

**Eclipse Version** 
Eclipse IDE for Java Developers
Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200

**Error Details**
'Installing Software' has encountered a problem:

An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: https://cucumber.io/cucumber-eclipse/update-site/plugins/cucumber.eclipse.editor_0.0.22.201806032001.jar.
https://cucumber.io/cucumber-eclipse/update-site/plugins/cucumber.eclipse.editor_0.0.22.201806032001.jar
Artifact not found: https://cucumber.io/cucumber-eclipse/update-site/plugins/cucumber.eclipse.steps.integration_0.0.22.201806032001.jar.
https://cucumber.io/cucumber-eclipse/update-site/plugins/cucumber.eclipse.steps.integration_0.0.22.201806032001.jar
Artifact not found: https://cucumber.io/cucumber-eclipse/update-site/plugins/cucumber.eclipse.steps.jdt_0.0.22.201806032001.jar.
https://cucumber.io/cucumber-eclipse/update-site/plugins/cucumber.eclipse.steps.jdt_0.0.22.201806032001.jar

![image](https://user-images.githubusercontent.com/26281892/41960430-1223218a-7a33-11e8-91bf-a6d86558aae9.png)

**Comment by jkuester** [comment]
I am seeing the same issue on the same version of Eclipse.  

The only difference is that I have an older version of the cucumber-eclipse plugin installed and I see this error when I try to update it.

**Comment by johny2000uwb** [comment]
@girijant  please let me know, what i did wrong.

**Comment by girijant** [comment]
@punarjit-singh , @jkuester ,
Thanks for your quick ticket. I fixed the issue in our repositroy for the latest release i.e. **0.0.22 (0.0.22.201806032001).**
Also updated our cucumber-plugin version in Eclipse-Market-Place with the latest release i.e. 0.0.22 (0.0.22.201806032001).

Please refer our 
[Eclipse-Market-Place URL](https://marketplace.eclipse.org/content/cucumber-eclipse-plugin) 
OR
[Plugin-Update-Site-URL](https://cucumber.io/cucumber-eclipse/update-site)
for latest plugin installation from Eclipse-IDE.

I also tested and installed successfully with my Eclipse IDE (i.e. Oxygen edition) as below:
```
Eclipse Java EE IDE for Web Developers. 
Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200
```
Please find below snapshots while installing the latest plugin version (0.0.22.201806032001) from both [Eclipse-Market-Place](https://marketplace.eclipse.org/content/cucumber-eclipse-plugin) and [Update-Site-URL](https://cucumber.io/cucumber-eclipse/update-site): 
**A. From our [Eclipse-Market-Place](https://cucumber.io/cucumber-eclipse/update-site):**
![install_1_0 22](https://user-images.githubusercontent.com/17194046/41987439-c50f3284-7a56-11e8-9de4-314077c7a00b.png)
![install_2_0 22](https://user-images.githubusercontent.com/17194046/41987455-cc51f7a2-7a56-11e8-9df6-05be85a53b98.png)
![install_success_0 22](https://user-images.githubusercontent.com/17194046/41987461-d1643cbe-7a56-11e8-883c-f0e720ff8c59.png)

**B. From our [Update-Site-URL](https://cucumber.io/cucumber-eclipse/update-site):**
![install_1_0 22](https://user-images.githubusercontent.com/17194046/41987596-45832d30-7a57-11e8-9a8f-f701e3a3620b.png)
![install_2_0 22](https://user-images.githubusercontent.com/17194046/41987604-48bec9dc-7a57-11e8-8ccf-45113f7e42fb.png)
![install_3_0 22](https://user-images.githubusercontent.com/17194046/41987608-4c88af92-7a57-11e8-8b15-78a00b15305a.png)
![install_success_0 22](https://user-images.githubusercontent.com/17194046/41987614-4fd23510-7a57-11e8-82c3-0a09f7ec8bdd.png)

**Comment by girijant** [comment]
@johny2000uwb,
You wrongly placed all 0.0.22-plugin-jars into 'update-site/feature' folder of 'gh-pages' branch. You MUST have to update the 'site.xml' file with the latest feature-version.

**Comment by johny2000uwb** [comment]
@girijant Ok, i see. We should update the contribution doku.
