### ISSUE TITLE
Steps definitions

### ISSUE THREAD

**Issue by Hugale12** [cucumber/cucumber-eclipse#274]
Hi everyone !

I have a problem when i lunch a feature :  right click -> run as -> cucumber feature

this return to me that in console : 

```java
 You can implement missing steps with the snippets below:

Given("I open a browser", () -> {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
});

When("I navigate to google page", () -> {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
});

Then("I validate the search text field", () -> {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}); 
```

But i don't understand, cucumber use annotations no ?    @Given etc...

```java
public class MyStepdefs {
    @Given("I have (\\d+) cukes in my belly")
    public void i_have_n_cukes_in_my_belly(int cukes) {
        System.out.format("Cukes: %n\n", cukes);
    }
}
```

So what's the mistake ? How writte correctly that ? 

Thx's a lot for help me =) !

**Comment by Hugale12** [comment]
I have finally found, just read the doc ... sorry

**Comment by DhavalSonejiQA** [comment]
@Hugale12  I found the same error, Can you please help me out ?

**Comment by DhavalSonejiQA** [comment]
I have found the solution, The Query is resolved.

**Comment by sujith1994** [comment]
> I have finally found, just read the doc ... sorry

@Hugale12 Could you help to fix this?Documentation link is 404. How you fix this

**Comment by titan1978** [comment]
Funny how people write "I found the solution" and dont bother actually writing it leaving the actual problem statement open.

**Comment by Hugale12** [comment]
> Funny how people write "I found the solution" and dont bother actually writing it leaving the actual problem statement open.

Sorry but this issue was closed 3 years ago...

I don't remember exactly the problem, but you can open a new issue ! =)
