### ISSUE TITLE
Add Groovy support

### ISSUE THREAD

**Issue by ouryperd** [cucumber/cucumber-eclipse#275]
When linking feature files to steps, or when creating a new step definition, the plugin expects src/test/java  packages/directories, and .java extentions. Please allow for Groovy projects too.

**Comment by ouryperd** [comment]
+1 for src/test/groovy

**Comment by laeubi** [comment]
In fact it does not require any folder structure, but currently only java annotated files are supported

**Comment by ouryperd** [comment]
I mean +1 for Groovy support.

**Comment by laeubi** [comment]
See https://github.com/cucumber/cucumber-eclipse/issues/275
