### ISSUE TITLE
Plugin not suggested in Marketplace for .feature files

### ISSUE THREAD

**Issue by jelaby** [cucumber/cucumber-eclipse#276]
If you open a .feature file without any supporting plugins, Eclipse informs you that there are Marketplace plugins available that support the file extension. If you go to the Marketplace, the only extension shown is the "Natural 0.7.6" plugin.

I think that this might be because the Natural plugin is tagged with `fileExtension_feature`, which is picked up by a search for `fileExtension:feature`.

The Natural plugin is nowhere near as good as this one - you'd make a lot of people happy if you made this plugin easier to find!

**Comment by qvdk** [comment]
I don't know how Eclipse Marketplace works to reference plugin support in function of a file extension.
By comparing the Natural plugin definition, I suppose the cucumber-eclipse plugin should have a `documentProvider` : 

```xml
<extension point="org.eclipse.ui.editors.documentProviders"> 
    <provider 
        extensions="jav" 
        class="org.eclipse.ui.examples.javaeditor.JavaDocumentProvider" 
        id="org.eclipse.ui.examples.javaeditor.JavaDocumentProvider"> 
    </provider> 
</extension> 
```

**Comment by qvdk** [comment]
@girijant can you add the tag `fileExtension_feature` to the plugin description on Eclipse Marketplace ? Thank you !

**Comment by girijant** [comment]
@qvdk, @jelaby,
Added 'fileExtension_feature' and 'fileExtension_story' tags for cucumebr-eclipse plugin description in Eclipse Marketplace.
![tags_eclipsemarketplace](https://user-images.githubusercontent.com/17194046/49215431-c9e82380-f3ee-11e8-8faa-249263d20023.png)

Thanks,
-Girija
