### ISSUE TITLE
Add support to show each step definition in the Outline panel

### ISSUE THREAD

**Issue by johno1985** [cucumber/cucumber-eclipse#277]
Since migrating our step definitions from methods to lambdas, we can no longer see the step definitions in the class Outline panel. It would be nice them in the Outline panel, similar to how you see scenario definitions in the feature file

**Comment by qvdk** [comment]
Are you talking about this ? 

![peek 2018-11-20 00-28](https://user-images.githubusercontent.com/6142398/48741411-46df0480-ec5b-11e8-8c9d-57a37c5ecf60.gif)

In this case, this is not a function of this plugin. This is managed by the eclipse JDT plugin with its Java editor.

**Comment by girijant** [comment]
Closing this ticket as this is invalid.
