### ISSUE TITLE
Very slow opening feature file

### ISSUE THREAD

**Issue by gilesn** [cucumber/cucumber-eclipse#281]
It's taking 35s to open a 2k file with 1 feature having 2 scenario outlines.

Using Eclipse Photon 4.8 20180619-1200 and Cucumber Eclipse Feature 0.0.22.201806032001

**Comment by carlduranleau** [comment]
Same thing here. I had this issue with Oxygen and Photon. There's no log while waiting for the .feature file to open. It just seems to wait for something that never happens. I've done all the updates without any success. I was running Cucumber plugin 0.18 and I tried updating to the latest 0.22, but the behavior is exactly the same. 

I'm running Ubuntu 18.04.1

**Comment by girijant** [comment]
@gilesn, 
Let me check this issue and will update soon.

Thanks,
-Girija

**Comment by carlduranleau** [comment]
Just to add information to the case, when trying to open a .feature file, or use the 'Find step' option, Eclipse is taking a complete CPU core at 100%. My PC is an i7-4820K with 16gb of RAM, so the hardware configuration shoudn't be a problem.

**Comment by gilesn** [comment]
OK thanks

**Comment by broun7** [comment]
I have the same experience with when using cucumber plugin with eclipse Photon.
Opening feature file: Takes along time, roughly > 30 secs.
Find step: Multiple minutes.
During the entire time the eclipse is unresponsive.

**Comment by rajkon** [comment]
In spite of these nice configuration I too face the same issue. It is so slow (>30 seconds) in opening feature file in Eclipse Photon. 2.)  Even if you click on tab that has feature file already open it takes the same amount of time. 3.) Even if you click a feature file directly in the Project Explorer it still takes the same amount of time.

Intel Core i7  -4800MQ CPU @ 2.70 GHz 2.69 Ghz
32 GB RAM 
64-bit OS, x64-based processor
Windows 10 Q2-2018

**Comment by Jalaliel** [comment]
I had the same problem and that was because I had a huge project with many different files. So the plugin was trying to scan them all, hence the slow opening. Indicating more precisely where the step definitions are solved the problem for me
![image](https://user-images.githubusercontent.com/26480018/47156141-be311980-d2e6-11e8-987e-2a6f9a850d2b.png)

**Comment by rajkon** [comment]
> I had the same problem and that was because I had a huge project with many different files. So the plugin was trying to scan them all, hence the slow opening. Indicating more precisely where the step definitions are solved the problem for me
> ![image](https://user-images.githubusercontent.com/26480018/47156141-be311980-d2e6-11e8-987e-2a6f9a850d2b.png)

@Jalaliel  can you please give an example as well.

**Comment by rajkon** [comment]
@Jalaliel can you please give an example as well.

**Comment by CandyLuWang** [comment]
Hi, I had same issue here, and all the automation test cases are written in Cucumber, now this issue really caused low work efficiency in my team. Could you please check this issue? Thank you very much.

**Comment by Jalaliel** [comment]
You just need to write in the box the name of the package where your step definition is (the smaller the package is, the faster the .feature files will open). I can't post you what works for me...

**Comment by automationsortie** [comment]
@Jalaliel , can you please give an example package to write in textbox. suppose there is package named stepDefinitions under which all step definition files are there thus we need to write stepDefinitions  in textbox, thats all?

**Comment by automationsortie** [comment]
Latest cucumber plugin is trouble some, folks anybody has got solution to install previous version where this textbox is not available and was working fine, this textbox is introduced in this 0.0.22 release only.
![image](https://user-images.githubusercontent.com/42842592/47472995-5d499a00-d82e-11e8-872c-d30987c3ee8e.png)

**Comment by Jalaliel** [comment]
@automationsortie yes that's all for me. And f3 works  with my workspace

**Comment by johny2000uwb** [comment]
I have add this box. The problem with slow open the file has been add in version 21. I have add feature with this box into version 22. Unfortunately, i have now no time to improve this plugin, but this can help.
The Problem with speed has been made with this PR
https://github.com/cucumber/cucumber-eclipse/pull/255/commits

**Comment by gilesn** [comment]
Thanks @Jalaliel, adding the step defs specific package in the text box effectively solves the performance issue.

**Comment by Silverhornet** [comment]
Unfortunately the fix is only applicable, under the assumption that all step definitions are located in the same name space. When the step definition of your projects are distributed under roughly 40 different name spaces, this does not do much good.

**Comment by CandyLuWang** [comment]
@Jalaliel , your solution working for me, it's much faster, thanks a lot!

**Comment by laks-martha** [comment]
@qvdk I am using mac system. After applying v0.0.23 update, we are seeing warning messages that steps are not implemented even though they are implemented.  I ran tests and they are also working fine. so these warning messages are misleading. I have to revert this to make it normal.

**Comment by Silverhornet** [comment]
Running the Step search in the background helps quite a lot, even though it still takes app 2-4 min. to finish. 
However, I experience quite often that multible eclipse background jobs are running at the same time, searching for steps (up 8 or 9 simultaneously) this in return makes eclipse unresponsive for up to 8 or 9 min. some times
![trunk - maqgen-lung-dna-ivd-plugin_src_accepttest_java_com_clcbio_bc_seqflowivd_-000147](https://user-images.githubusercontent.com/10836941/50143188-45314c80-02ac-11e9-8339-44e5284df222.png)

I have not yet identified a consistent way of reproducing the situation, but i'm seeing it several times every day, and it seems to occur when i'm switching between and editing multiple step definition files and feature files in Eclipse.

Cucumber plugin version: v0.0.23
Eclipse version: Photon Release (4.8.0)
Java build version: 1.8.0_172-b11

**Comment by qvdk** [comment]
Hi @Silverhornet 

Thanks a lot for your feedback !

I am currently working on this issue. Effectively the step definitions scans is launched too often. There are many reason why I described them in #305 

As you reproduce the bugs many times a day, could you test a snapshot version and give me your feedback?

It is a **beta** version but you could help me a lot if you have often this issue to validate the improvement.
https://github.com/qvdk/cucumber-eclipse/tree/improvements/step_detections_optimization/cucumber.eclipse.download/download/1.0.0-SNAPSHOT

**Comment by Silverhornet** [comment]
Hi @qvdk 
I have uninstalled uninstalled the v0.0.23 plugin and installed the one you shared.
However it seems that the cucumber plugin does not scan for step definitions at all now, nither when i open af feature file, hit F5 or F3 nor when I right click and select "recalculate steps" or "Find step definition".

The plugin seems to be operational (pretty formart and keyword highlighting works and configuration is available in preferences)

**Comment by Silverhornet** [comment]
@qvdk 
my bad, misset that point :)

I have a problem though. When converting the projects to a Cucumber project, it seems to mess up the project file, such that the CheckstyleBuilder is executed before the javabuilder. 
![image](https://user-images.githubusercontent.com/10836941/50161202-665d6180-02db-11e9-9a62-7db2bc88d2a4.png)
This causes checkstyle to fail as it must be run after the javabuilder. 
`The project xxx cannot be checked by Checkstyle because the Checkstyle Builder is set to run before the Java Builder. Please go to Project->Properties->Builders and change the Builder ordering that the Checkstyle Builder runs after the Java Builder.`

This is a problem as I need to do this for 60+ projects.

I'll try i out briefly as this is somewhat deseruptiv to my paid work

**Comment by qvdk** [comment]
Thanks for the report.

The latest snapshot fixes it. Can you retry ?

**Comment by Silverhornet** [comment]
I'm on it. 
will return later today with feed back :)

**Comment by Silverhornet** [comment]
It Seems to have fixed the project set up proplem and it seems to performe nicely (only slightly interesse to build times in Eclipse) :)

But i do still see som problems. 
We have a few projects that fail when i convert them to cucumber projects.
[Eclipse-error-log-convert-configuration.txt](https://github.com/cucumber/cucumber-eclipse/files/2694545/Eclipse-error-log-convert-configuration.txt)

Excluding those projects, all seems to work ok.
However when i restart eclipse i get another error from Eclipse.
[Eclipse-error-log-restart.txt](https://github.com/cucumber/cucumber-eclipse/files/2694587/Eclipse-error-log-restart.txt)
The plugin no longer map any of the steps to their respective step definitions.

**Workaround** is to run "Eclipse:Project>Clean>all projects" which seem to fix the issue until next restart of eclipse.

**Comment by qvdk** [comment]
The first issue is related to the builder. The Cucumber project conversion seems to work since the builder is launched.
However, this issue seems related to a regular expression from one of your step definition. And probably a known issue on [cucumber-expression#510](https://github.com/cucumber/cucumber/issues/510). Do you have a regular expression using the negative lookahead ? Could you provide the regexp to reproduce the issue ?

For the second one, I should improve my solution about markers. The ones keeps the step definition, but its serialization generate too big data in your case.

About the workaround, the clean works when associated with the auto build, else you have to launch manually the build.

Thanks again for your feedback.

**Comment by qvdk** [comment]
I updated the v1.0.0-SNAPSHOT. 

I fix both errors. 
So, the build should now pass.

However for the first error, I fix the crash but you will probably have an unmatched step because one of your step definition have an unsupported regex.

**Comment by Silverhornet** [comment]
Looked in to the part about 'negative look behind' but did not find any. I did however find an 'atomic group' '(?>...)' 

The cucumber seem to be faster, in turn it seem to be building a bit excessively (does not seem to be a pain yet)

However the problem regarding restart does persit. However with a nev error:
[feail-on-restart.txt](https://github.com/cucumber/cucumber-eclipse/files/2699337/feail-on-restart.txt)
I get many of them and they alle seem to have in common to target files in resources ending on ...Report.txt
e.g.
> L/xxx/src/accepttest/resource/snapshot-expected/yyy/zzzReport.txt
