### ISSUE TITLE
Step definitions are only matched against glue code in the same project

### ISSUE THREAD

**Issue by karypid** [cucumber/cucumber-eclipse#287]
[multiproject-stepdefs.zip](https://github.com/cucumber/cucumber-eclipse/files/2480820/multiproject-stepdefs.zip)

As per the attached example, step definitions whose glue code is in a separate project from the feature file are not matched.

When the preference page fore user settings has specific package names defined, then the entire classpath should be scanned for possible glue code to be matched.

**Comment by laeubi** [comment]
Since we have the same issue, I'll take a look at it, thanks for the example
