### ISSUE TITLE
Download a specific version

### ISSUE THREAD

**Issue by CandyLuWang** [cucumber/cucumber-eclipse#288]
Hi,
Could anyone please let me know how can I download a specific version of cucumber plugin? Since with the latest cucumber plugin, open a feature file is super slow. Thank you very much.

**Comment by jkuester** [comment]
I believe you can just pull down older versions of the plugin here: https://github.com/cucumber/cucumber-eclipse/tree/master/cucumber.eclipse.download/download

To install the older version in Eclipse, you would need to download and unzip the plugin.  Then in Eclipse navigate to Help > Install New Software.  In the "Work with:" box enter the path to your unzipped plugin folder (e.g. file:/C:/Users/myUser/Downloads/cucumber-eclipse-plugin-0.0.19-SNAPSHOT/).

Then you should be able to select the Cucumber Eclipse Plugin to install by following the rest of the wizard.

**Comment by laeubi** [comment]
@CandyLuWang Can you provide a sample project that demonstrate the "super-slow" opening?

**Comment by girijant** [comment]
@CandyLuWang,
You may install our plugin via Eclipse from our Eclipse Marketplace : https://marketplace.eclipse.org/content/cucumber-eclipse-plugin

Thanks,
-Girija
