### ISSUE TITLE
Support custom parameter type

### ISSUE THREAD

**Issue by qvdk** [cucumber/cucumber-eclipse#291]
Cucumber expressions are supported since #285 

However, only built-in parameter types are supported. 
For example: `I have a {word} ball`.

There are other built-in parameter types like `{int}`, `{float}` or `{string}`. The full list of [built-in parameter types](https://docs.cucumber.io/cucumber/cucumber-expressions/) is available in the cucumber docs.

But cucumber expressions allow to supply your own parameter type.
For example: `I have a {color} ball`

You can define your `color` parameter type with the following snippet: 
```java
typeRegistry.defineParameterType(new ParameterType<>(
    "color",           // name
    "red|blue|yellow", // regexp
    Color.class,       // type
    Color::new         // transformer function
))
```
The previous link on the documentation provides more details.

For now, the plugin does not detect cucumber expressions with custom parameter type. 
So, the steps written with these ones are detected with no matching glue code. 

![screenshot from 2018-11-22 02-02-50](https://user-images.githubusercontent.com/6142398/48875708-c6570a00-edfa-11e8-8919-7dc251db670a.png)

More, the user can not jump to the matching glue code with <kbd>CTRL</kbd>+<kbd>click</kbd> or <kbd>F3</kbd>.

The issue comes with the following snippet from cucumber.eclipse.steps.integration.Step.setText(String)
```java
this.expression = new ExpressionFactory(new ParameterTypeRegistry(locale)).createExpression(text);
```

In order to support custom parameter type, the plugin should retrieve all `ParameterType` available in the classpath, then register them to the `ParameterTypeRegistry`. 

The issue can be reproduced with the [java-calculator sample project](https://github.com/cucumber/cucumber-jvm/tree/master/examples/java-calculator).

**Comment by laeubi** [comment]
@qvdk do you plan to supply a patch or is help needed in this area? I would like to see this supported because we need it for one of our projects as well.
I think cucumber eclipse should scan for TypeRegistryConfigurer instead, and call the TypeRegistryConfiguration#configureTypeRegistry(TypeRegistry) instead, because we do not know in advance what are the parameters, and the configurer is neede already to let Cucumber find the custom type if I read this right https://docs.cucumber.io/cucumber/configuration/ this would also be needed for custom parameter type converter.

**Comment by qvdk** [comment]
@laeubi help needed :+1: 

Your are  right. Ideally, the plugin should search after `TypeRegistryConfigurer`.

However, I do not known how to get, compile and execute the previous search results.

**Comment by laeubi** [comment]
Allright, I'll try to provide a fix for that in the next days!

**Comment by laeubi** [comment]
I'm able to load the typeconfigurer now but there is some kind of refactoring required to support it in the step.
The second problem is, that the plugin uses rather old cucumber version (1.2, emebeded in the plugins) that need to be updated, but the API has changed. One restriction would be, that the typeconfigurer version must be compatible with the version cucumber-eclipse uses, so I think we definately should not embedd the jars, but get them from an offcial update site, or download them from maven so it is easy to keep up with updates

**Comment by qvdk** [comment]
Hi @laeubi 

> I'm able to load the typeconfigurer now but there is some kind of refactoring required to support it in the step.

Nice ! Could you share the branch on your fork ? I could help.

> The second problem is, that the plugin uses rather old cucumber version (1.2, emebeded in the plugins) that need to be updated, but the API has changed. 

Yes, the library should be updated but this causes many changes. The API changes for cucumber, but also for the gherkin parser.

Note, I had introduce the cucumber-expression-6.1.0 library to support cucumber expressions.

The cucumber expressions was introduce last year in cucumber itself. Then, they did not exist for the cucumber-core-1.2 version.

But this is not a problem, because the cucumber-core-1.2 is not use to parse feature file (only the gherkin dependency, but this language have not change since long time).

More, only cucumber-expression-6.1.0 is used to parse cucumber expressions, plus the classes `ParameterType` and  `ParameterTypeRegistry` are from the same jar : cucumber-expression-6.1.0.
So, we could use them to initialize the `ExpressionFactory`.

>  that the typeconfigurer version must be compatible with the version cucumber-eclipse uses

By chance, we did not need the `TypeRegistryConfigurer` but the `ParameterTypeRegistry`. I did a confusion.

So, I think we could add the support of custom parameter types without upgrade entierly the cucumber dependency.

This upgrade could be done later.

> so I think we definately should not embedd the jars, but get them from an offcial update site, or download them from maven so it is easy to keep up with updates

Maybe the plugin need improvements about dependency management.
We could take a look at this article : https://wiki.eclipse.org/Tycho/How_Tos/Dependency_on_pom-first_artifacts

However, for the launch of cucumber when using Run As > Cucumber feature from a feature file, I think the plugin should use an external installation of cucumber, as Eclipse done with external JRE instead of an internal launch of the library. Or, a best way could to use the internal dependencies by default, and allow to use an external installation of cucumber. 

This could be a new feature which allow to support any recent cucumber release independently of the version used by the plugin.

**Comment by laeubi** [comment]
> Nice ! Could you share the branch on your fork ?
I need to cleanup everything a bit first since it is very experimental.

> We could take a look at this article
The problem with tycho aproach is, that is is really hard do develop/test such projects, because you can't really start them from the IDE as regular bundles but must take a full buildrun.

As a first step, we should add osgi-manifest headers to the cucumber base jars (core, jvm etc..) so they can be used inside OSGi (with the bnd-maven-plugin). Then we can create an updatesite from them (with tycho) that  can be used in the eclipse-cucumber plugin.
For now, we might create one dedicated bundle that embedds the jars and export the packages with proper version we need internally?

I think it would be good to lauch by default with internal cucumber, and maybe support external installations as you suggested, this is how it works for maven, ant and other tools afaik also...

But to call classes from client code they must be compatible with internal cucumber, but as you have mentioned there won't be much API changes, but we should take this in mind.

**Comment by laeubi** [comment]
Currently libs used across projects:

- cucumber-core-1.2.5
- cucumber-core-1.2.2
- cucumber-java-1.2.2
- cucumber-expresions-6.1.0
- gherkin-2.12.2

**Comment by laeubi** [comment]
@qvdk I'm currently a bit stucked at the StepMatcher class, since it seems to modify steps before checking if they match a line, do you have an idea what this class does? Why not simply call step.matches? Shouldn't all that quirks be handled in the Expression instead of the ui code?

**Comment by laeubi** [comment]
![grafik](https://user-images.githubusercontent.com/1331477/49279939-197b2d80-f489-11e8-8033-7a3c2d6c36f9.png)
As a first step I refactored the Step class to be final regarding to its members (it should realy not be modified in any way after creation), and added error markers in case that an expression can't be parsed, I think this is much more convenient than simply ignore the error and present the expression to the user.

**Comment by laeubi** [comment]
Okay, I think I got it, thats really nasty since it modifies the pattern to match much more, I have to think about how we can handle this more nicely. The problem here is, that in fact we must generate a complete new step just for matching. Also the method relies on the fact that it has a regular expression that can be converted, so we might can operate on the regular expresion of the step instead, but I don't like the aproach.

**Comment by laeubi** [comment]
> By chance, we did not need the `TypeRegistryConfigurer` but the `ParameterTypeRegistry`. I did a confusion.

Do you have any reference how it works, TypeRegistryConfigurer is part of cucumber-core, thats the problem. The core package is also used to generate missing steps so I thing it would be good to upgrade anyways...

**Comment by laeubi** [comment]
This becomes more and more a Nightmare... Upgrading the cucumber-libs would require to upgrade the gherkin-parser, that has changed alot. Also the latest gherkin parser uses GO binaries to parse the feature file (eek!) and blows up to 45Mb (from 300kb).
The most noteable feature that is affected here is the "generate step" Quick-Fix, don't know if we can drop this for now...

**Comment by laeubi** [comment]
I haved pushed https://github.com/cucumber/cucumber-eclipse/tree/issues/291 with the current work, it can now parse expressions with custom types without a problem (you get a red x if parsing failed, e.g. type not configured), jsut the matching does not seem to work (or my Configuration is wrong...)

**Comment by mpkorstanje** [comment]
> This becomes more and more a Nightmare... Upgrading the cucumber-libs would require to upgrade the gherkin-parser, that has changed alot. Also the latest gherkin parser uses GO binaries to parse the feature file (eek!) and blows up to 45Mb (from 300kb).

You only have to upgrade to Gherkin v5. Not v6.

**Comment by qvdk** [comment]
@laubi `io.cucumber.cucumberexpressions.ParameterTypeRegistry.ParameterTypeRegistry(Locale)` comes from cucumber-expression jar file. So, the cucumber-core upgrade is not necessary for this feature.

But, the upgrade of the cucumber-jvm should be done, preferably for a new feature, I think. There are effectivelly many works, notably for the gherkin parser totally rewritted. But the current one does not have a really nice parser functions.

> @qvdk I'm currently a bit stucked at the StepMatcher class, since it seems to modify steps before checking if they match a line, do you have an idea what this class does? Why not simply call step.matches? 

The `StepMatcher` does not make the same work than the `Step.matches`.
The first parse expressions like `Given I have a cat`, the second only `I have a cat`.
Thus, the `StepMatcher` manages i18n for Gherkin keywords, for example.

Theses classes are not intend to replace the gherkin parser, they are here to make the glue between Gherkin and Java sources.

The plugin itselft does not directly depends of the Gherkin library. This is a transitive dependency of cucumber-jvm. 

As @mpkorstanje explained, the plugin does not need of a Gherkin v6 upgrade, since it need an upgrade of cucumber-jvm. This last uses the Gherkin v5.1.0.

> Shouldn't all that quirks be handled in the Expression instead of the ui code?

You are right, but the plugin needs to analyse a minimum to complete the glue.
More impresivly, the plugin should delegate all parsing and actions to cucumber-jvm. The plugin should only do its integration.

> The most noteable feature that is affected here is the "generate step" Quick-Fix, don't know if we can drop this for now...

It is an important feature, and helpful. 

> I haved pushed https://github.com/cucumber/cucumber-eclipse/tree/issues/291 with the current work, it can now parse expressions with custom types without a problem (you get a red x if parsing failed, e.g. type not configured), jsut the matching does not seem to work (or my Configuration is wrong...)

I will take a look soon to your branch. The matching was improved from the v0.0.22, and your branch is behind master, maybe some issues will be solved.

**Comment by qvdk** [comment]
> his becomes more and more a Nightmare...

@laeubi And the more important, keep it a pleasure ;) It is not a nightmare, just an other challenge :)

**Comment by mpkorstanje** [comment]
Yes! And if it turns out a better interface is needed to support platforms we can build that! 

I am currently working on a JUnit Platform implementation of Cucumber. This supports, running selecting and discovery of features through a standard API.

So suppose you have an instance of the CucumberTestEngine. What would you ask it? List defined stepdefinitions? Given a set of steps, tell you which match and in which file? Anything else?

**Comment by mpkorstanje** [comment]
Not saying we'll build it right now, this instance, but we should have path away from custom code and towards dependencies on stable interfaces.

**Comment by laeubi** [comment]
> `io.cucumber.cucumberexpressions.ParameterTypeRegistry.ParameterTypeRegistry(Locale)` comes from cucumber-expression jar file. So, the cucumber-core upgrade is not necessary for this feature.

But you can't use this directly! Look at the branch what is implemented by clients code is TypeRegistryConfigurer and it even uses a diferent "TypeRegistry" so I have to implement an Adapter...

**Comment by laeubi** [comment]
@qvdk I updated the branch with latest master

**Comment by qvdk** [comment]
> So suppose you have an instance of the CucumberTestEngine. What would you ask it? List defined stepdefinitions? Given a set of steps, tell you which match and in which file? Anything else?

@mpkorstanje the plugin does not delegate enough for now in my opinion. Idealy the engine should be implemented into cucumber-jvm.

 - list step definitions 
 - list gherkin steps and their related step definitions locations
 - generate step definitions source code from a single / severals gherkin steps, or a full gherkin feature file in any jvm languages (java, but also kotlin or groovy)
 - step definitions parsing error management. For example, when a user make a mistake on a step definition `@Then("^this is an invalid {word} cucumber expression")`

All this features are already available in cucumber-jvm, I think.

**Comment by laeubi** [comment]
A first implementation is available in the master, we should track any issues/enhancements with this in new tickets.
