### ISSUE TITLE
`Go to StepDef` throw an error when the first feature file opened from a closed project

### ISSUE THREAD

**Issue by qvdk** [cucumber/cucumber-eclipse#295]
```gherkin
Given I have 2 projects with feature files
   And I opened a feature file in the first project
   And I closed this first project 
 When I open a feature file from the second project with F3 key
  Then the editor jump to the step definition
    But an error occurs
```
;) 

This is due to the `ExtensionRegistryStepProvider` associated with a file. This contructor expects a file `ExtensionRegistryStepProvider(IFile file)`. The argument file is a feature file.
But the reference is kept yet when the project of this feature file is closed.
Then, the next time the user opens a feature,  the step detection starts and the `ExtensionRegistryStepProvider` attempts to get referenced projects on a closed project.
 This is the root cause of the error. 

![peek 2018-11-24 03-36](https://user-images.githubusercontent.com/6142398/48963810-4ddb7f00-ef9b-11e8-8ef4-e0b34d97b49c.gif)

**Comment by laeubi** [comment]
@qvdk I a project we are using SWT-Bot as a layer between Eclipse RCP and Cucumber so your example could be made to work if needed :-)
Beside this, RCPTT is a nice tool for Eclipse based UI tests, we might setup one for the cucumber eclipse part, or is there already something for UI tests?

**Comment by qvdk** [comment]
@laeubi You are right. The plugin lackes of automated tests.
There are someones units tests, but integration tests could be great.
