### ISSUE TITLE
Cucumber Plugin crashes when I enclose any word with double quotes in feature file. It is reproducible in the group io.cucumber and not in info.cukes group 

### ISSUE THREAD

**Issue by pavanswt** [cucumber/cucumber-eclipse#297]
Steps to Reproduce
=============

1.  Use the following maven dependency.

https://mvnrepository.com/artifact/io.cucumber/cucumber-junit

2. Create a feature file with a string parameter like below. 

Feature: Title of your feature
  I want to use this template for my feature file

  Scenario: Title of your scenario
    Given I want to write a step with the precondition
    When I complete action
    Then I validate the "Hello" text

3. Run as the feature file with cucumber JVM

4. Copy the snippets and put in to step def class file. 

5. Restart your eclipse and observe the feature file is crashed with the following error message. 

Illegal repetition near index 14
I validate the {string} text
              ^
Please find the attached screenshots and files for your reference. 
![stepdefinition file](https://user-images.githubusercontent.com/4628225/49025601-f2281600-f193-11e8-8a70-c52419d4818d.png)
![feature file](https://user-images.githubusercontent.com/4628225/49025603-f2281600-f193-11e8-92d3-1ce2d6bf524c.png)
![error message](https://user-images.githubusercontent.com/4628225/49025604-f2281600-f193-11e8-813a-9114b81b9cc1.png)

**Comment by qvdk** [comment]
Hi @pavanswt, 

Thank you for submitting bug report !
I am please to annonce you this issue was known, and the fix was ever done #285
It will be available in the next release.

If you want the fix before, you can build master or install manually the fix from https://github.com/qvdk/cucumber-eclipse/blob/release/0.0.23/cucumber.eclipse.download/download/0.0.23-SNAPSHOT/cucumber-eclipse-plugin-0.0.23-SNAPSHOT.zip

**Comment by pavanswt** [comment]
Hi Quentin,

Thank you for your email.

I am sorry to repeat the issue. I haven't seen that this issue is already
been open.

Anyways thank you Very much for suggesting snapshot version for the quick
work around.

Regards,
Pavan
