### ISSUE TITLE
Can't install STS and scala plugins through Eclipse Photon

### ISSUE THREAD

**Issue by MountingP** [cucumber/cucumber-eclipse#298]
I'm not able to install STS , it gave me an error.. Therefor I had to install it manually. The error I got as follows.

session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://download.springsource.com/release/TOOLS/update/3.9.6.RELEASE/e4.8/plugins/org.springframework.tooling.cloudfoundry.manifest.ls_0.3.2.201806290921.jar.
Read timed out
Unable to read repository at http://download.springsource.com/release/TOOLS/update/3.9.6.RELEASE/e4.8/plugins/org.springsource.ide.eclipse.commons.cloudfoundry.client.v2_3.9.6.201809180658-RELEASE.jar.
Read timed out
.. ...
And also I tried install Scala plugin. I experienced the same kind of issue. 
Could someone help me on this. 
Eclipse Version - Photon
Java - 1.8

**Comment by qvdk** [comment]
Hi @MountingP 

Sorry for your inconvenience but this project collect only issues about the Cucumber Eclipse plugin.

However, I could suggest you to download the latest ready-to-use STS bundle, then install the scala plug-in directly from the Eclipse Marketplace.

More a new STS version 4.0 is out: https://spring.io/tools

**Comment by MountingP** [comment]
Hi Quentin Vandekerckhove

 Thanks for your reply. And also I do apologize for publishing my issue in
your forum.
