### ISSUE TITLE
Allow multiple packages in the option "Only match steps from specific package and sub-packages"

### ISSUE THREAD

**Issue by jetrop** [cucumber/cucumber-eclipse#302]
Currently the step scan takes about 20 mins, and this happens every time I open a new feature file, so I used the "Only match steps from specific package and sub-packages" to specify the package where the steps are, and the feature files load within a couple of seconds now which is great.

However we have a couple of projects that have feature files and the steps for these are in different packages. We really need a way to specify more packages to scan.

Currently I have to keep changing the package in the cucumber options when switching between the 2 projects.

**Comment by qvdk** [comment]
Hi, @jetrop 

This is already availlable, simple use comma between packages. For examples: `com.package1,com.package2,org.package3`

I am currently working on an optimization for step definitions detection. Can you provide a sample to reproduce the 20 minutes loading ?
Or, could you test a beta version ?

**Comment by qvdk** [comment]
You are right. Setup a list of package is only available for external jars.

**Comment by laeubi** [comment]
What I have on my list is so scan for Annotated Test classes. There you can specify the packages to scan for Stepdefs and it would be good if this is used instead of some kind of config.

**Comment by girijant** [comment]
@qvdk, @laeubi,
As of now this feature like populating of steps from any packages/sub-packages of any ext-project (i.e. as a Ext-JAR/maven-dependencies or from project-class-path)is configurable( by comma sepatrated) via cucumber-settings of Eclipse. After discussing a lot with may intrnal and extenal teams, I prfered to implement it as a configurable via cucumber-settings of Eclipse instead of specifying package-scanning from any soruce-code(step-def files). Before enhancing this feature please consider the existing use cases i.e. widely used across many of internal teams in my company or external companies. 

@jetrop,
As of now I was parsing from JAR(.class) files which can be enhanced for Source file(.java) of ext project.
Please share your detail use-cases before enhancing this.

Thanks,
-Girija

**Comment by qvdk** [comment]
Hi @jetrop 

Could you try the [latest version 1.0.0-SNAPSHOT](https://github.com/cucumber/cucumber-eclipse/raw/master/cucumber.eclipse.download/download/1.0.0-SNAPSHOT/cucumber-eclipse-plugin-1.0.0-SNAPSHOT.zip) of the plugin with your project which took 20 minutes to scan step definitions and report your feedback please ?

Thank you

**Comment by jetrop** [comment]
Hi @qvdk 

There is no step scanning now, however the steps in the feature file are no longer validated. If I change a step to something invalid, it doesn't highlight it anymore.

Also I can no longer click on the step in the feature file to take me to the actual step code. F3 doesn't work either.

I've tried it with and without the Step Definitions filters, and also with the "Glue only gherkins and step definitions files in the same location" ticked and unticked.

**Comment by carlduranleau** [comment]
Using the latest Cucumber plugin `0.0.23.201811220126` and I can't use multiple package names in the configuration. And maybe I don't understand how it works, but to make the text field `Only match steps from specific package and sub-packages` work, I need to keep the checkbox `Only match steps from package and sub-packages` unchecked. I really don't get the point here.

If I don't check the box and set no package in the text field, I can't see the steps definition scanning process running when opening a feature file. But when checking the box, the process doesn't start anymore when opening a file. Is this a bug or simply a weird configuration design? If I leave the box unchecked and add a comma and second package name, the scanning process starts for half a second and stops without resolving anything. So adding more than one package name still not working in latest released version.

**Comment by qvdk** [comment]
@carlduranleau This feature is available since the 1.0.0-SNAPSHOT.
Please try the latest build: https://github.com/cucumber/cucumber-eclipse#follow-the-latest-snapshot
