### ISSUE TITLE
Editor fails, if step definitions have constructor with dependency injection like pico-container.

### ISSUE THREAD

**Issue by phanikshr** [cucumber/cucumber-eclipse#303]
Getting error message "An internal error occurred during: "Scanning for step definitions".
java.lang.NullPointerException"

My stepdef file looks like

public class mynewstepdefs{
        public String str1;
        public int int1;
  public mynewstepdefs(parallelcontext context){
   
}
}

**Comment by qvdk** [comment]
Hi @phanikshr 

The Cucumber Eclipse plugin does not use pico-container. Thus, your example can not work.

**Comment by mikejramsey56** [comment]
phanikshr (or anyone else who finds there way here) check if your step definition specified

<import cucumber.api.java.en.*;>

If so, simply replace it with


<import.api.java.en.Given;>
<import cucumber.api.java.en.Then;>
<import cucumber.api.java.en.When;>

**Comment by AlanBarrera** [comment]
@mikejramsey56 Brilliant!! That did the job for me. Thank you!

**Comment by qvdk** [comment]
Could you provide a sample to reproduce your issue please ?

**Comment by AlanBarrera** [comment]
@qvdk You can use my repo: 

https://github.com/AlanBarrera/CucumberExercisesRepo

In the _StepDefs_Register.java_ file, change this individual imports:

import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
import cucumber.api.java.en.When;

for:

import cucumber.api.java.en.*;

Then open the _Register.feature_ and an error window should prompt.

**Comment by qvdk** [comment]
Thanks @AlanBarrera I will take a look

**Comment by mikejramsey56** [comment]
Alan,
 It took a late evening to figure that one out.  Glad that it helped.

**Comment by skumardgl3** [comment]
> phanikshr (or anyone else who finds their way here) check if your step definition specified
> 
> `import cucumber.api.java.en.*;`
> 
> If so, simply replace it with
> 
> ```
> import cucumber.api.java.en.Given;
> import cucumber.api.java.en.Then;
> import cucumber.api.java.en.When;
> ```

It worked for me
Please explain the reason for this

**Comment by gliang-sugarcrm** [comment]
Thanks @mikejramsey56 ! Changing the '.*' to '.Then', 'When', ... etc works for me!

**Comment by gliang-sugarcrm** [comment]
I accidentally changed all the individual '.Then', '.When' ... to '.*' and hit the same issue immediately. Thanks again @mikejramsey56 .

**Comment by AmOkeyBright** [comment]
Please can anyone be of help to me.  I have having those yellow signs in my feature file which says  Step "XXXXXXX" does not have a matching glue code, though i have the step definitions. My feature files are in src/test/resources/Features folder while my stepDefinitions class are in src/test/java/steps package.  **I am relatively new to Cucumber**
![CucumberCapture](https://user-images.githubusercontent.com/51756222/62411844-b6363200-b5f9-11e9-844b-2048d144b790.PNG)
![CucumberGlueCode](https://user-images.githubusercontent.com/51756222/62411845-b6363200-b5f9-11e9-94de-b7aad5b46ab8.PNG)



These are my cucumber dependencies


	<dependency>
		<groupId>io.cucumber</groupId>
		<artifactId>cucumber-java</artifactId>
		<version>4.5.4</version>
	</dependency>

	
	<dependency>
		<groupId>io.cucumber</groupId>
		<artifactId>cucumber-testng</artifactId>
		<version>4.5.4</version>
	</dependency>

**Comment by gliang-sugarcrm** [comment]
If you right click on a step with yellow sign and click on “Find step”, does it find the step for you? (assuming you are using Eclipse for your cucumber java project)

**Comment by AlyyMagdy** [comment]
> Please can anyone be of help to me. I have having those yellow signs in my feature file which says Step "XXXXXXX" does not have a matching glue code, though i have the step definitions. My feature files are in src/test/resources/Features folder while my stepDefinitions class are in src/test/java/steps package. **I am relatively new to Cucumber**
> ![CucumberCapture](https://user-images.githubusercontent.com/51756222/62411844-b6363200-b5f9-11e9-844b-2048d144b790.PNG)
> ![CucumberGlueCode](https://user-images.githubusercontent.com/51756222/62411845-b6363200-b5f9-11e9-94de-b7aad5b46ab8.PNG)
> 
> These are my cucumber dependencies
> 
> ```
> <dependency>
> 	<groupId>io.cucumber</groupId>
> 	<artifactId>cucumber-java</artifactId>
> 	<version>4.5.4</version>
> </dependency>
> 
> 
> <dependency>
> 	<groupId>io.cucumber</groupId>
> 	<artifactId>cucumber-testng</artifactId>
> 	<version>4.5.4</version>
> </dependency>
> ```

If you're sure you include your step def file correct , just try to close the .feature file from your open tabs in eclipse and then open it again , you will notice the down in eclipse that there's a new scanning for step defs. Hope it will work with you!

**Comment by rakeshbg005** [comment]
HI,

you can refer this discussion to solve this issue
https://github.com/cucumber/cucumber-eclipse/issues/383

Thanks
Rakesh

**Comment by TomasMorton** [comment]
Why on earth is it necessary to import each keyword separately?
Thanks for the fix @mikejramsey56
