### ISSUE TITLE
Javascript instead of java step skeletons

### ISSUE THREAD

**Issue by zadigus** [cucumber/cucumber-eclipse#317]
Hi,
In my Java project, when I run the cucumber tests without step definitions, cucumber generates step definition skeletons. Unfortunately, the generated code is javascript, not java. Do you happen to know what I need to configure to make it work? I am not sure it is due to cucumber-eclipse plugin, though, because I tried the same with Natural and I get the same result. 

Here's my configuration:

```
<aspectj.version>1.9.2</aspectj.version>
<cucumber.version>4.2.0</cucumber.version>
<hibernate.version>5.4.0.Final</hibernate.version>
<junit.version>4.12</junit.version>
<maven.compiler.source>1.11</maven.compiler.source>
<maven.compiler.target>1.11</maven.compiler.target>
<mysql.version>8.0.13</mysql.version>
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<spring.version>5.1.3.RELEASE</spring.version>
```

Thanks in advance

**Comment by mpkorstanje** [comment]
Are you using `cucumber-java8` by any chance?

**Comment by zadigus** [comment]
Yes I do. Do the generated skeletons actually correspond to new allowed syntax with lambdas?

**Comment by mpkorstanje** [comment]
That is correct.
