### ISSUE TITLE
Error: Could not find or load main class cucumber.api.cli.Main

### ISSUE THREAD

**Issue by jainsampada** [cucumber/cucumber-eclipse#330]
Error: Could not find or load main class cucumber.api.cli.Main while running feature file in Maven

**Comment by girijant** [comment]
@jainsampada
Have you tried to it from Eclipse ??? Try it from command prompt without using Eclipse.
Please share the detail exception stack trace with your eclipse and cucumebr-plugin version. 

Thanks,
-Girija

**Comment by laeubi** [comment]
I also see this problem, beside this the Run As>Cucumber-Feature is broken in recent eclipse versions, this is due to the unimplemented 
`void launch(ISelection selection, String mode)`

**Comment by laeubi** [comment]
The problem seems that the classpath does only contain user entries when computed by the runner and not the eclipse classpath.

**Comment by laeubi** [comment]
Duplicate of #190

**Comment by shilpijoshi22** [comment]
> @jainsampada
> Have you tried it from Eclipse or without Eclipse??? Try it from command prompt without using Eclipse.
> Please share the detail exception stack trace with your eclipse and cucumebr-plugin version.
> 
> Thanks,
> -Girija

@girijant I am using command promt to run this. But I am unable to understand the syntax and use. Can you please help

**Comment by 11nidhi** [comment]
> I also see this problem, beside this the Run As>Cucumber-Feature is broken in recent eclipse versions, this is due to the unimplemented `void launch(ISelection selection, String mode)`

Can you suggest any solutions?
Like i didn't get what to do exactly to resolve this
