### ISSUE TITLE
Builder does too much work

### ISSUE THREAD

**Issue by vladdu** [cucumber/cucumber-eclipse#334]
When building incrementally, if a change to a file including step definitions is discovered, the a full rebuild is done because the changes could affect any part of the code. 

This is cool, but the implementation just calls the fullBuild() method, meaning that if for example there are changes to five such files, the full build is done five times.

We should set a flag and do the full build just once.

**Comment by vladdu** [comment]
related to #325

**Comment by qvdk** [comment]
There are 2 builders. One for the step definition detection and another for the gherkin step glue detection.
Only this last should always perform a full build since any change about steps definitions can affect the glue.

Can you explain how reproduce the five time build ?
