### ISSUE TITLE
Is there any ETA for eclipse 2019.03 aka 4.11?

### ISSUE THREAD

**Issue by kingoleg** [cucumber/cucumber-eclipse#350]
Hi,

Can we have a new version that support the latest eclipse version?

Regards,
Oleg

**Comment by laeubi** [comment]
I think it would help if you describe what does not work... Do you get any error? incompatible imports? Other issues?

**Comment by qvdk** [comment]
Do you install the latest version from Eclipse Marketplace or the latest snapshot ?

**Comment by kingoleg** [comment]
I tried to install it from Eclipse Marketplace But it's impossible. Eclipse deny it, I think, because it's marked as incompatible with 2019.03. Should I use the latest snapshot?

**Comment by qvdk** [comment]
Yes the latest snapshot should be compliant.
More, there are a dedicated eclipse update site to be kept up-to-date with the latest development version.
Instructions on how to install it are availables here : https://github.com/cucumber/cucumber-eclipse

Please let us to know if this version solves your issue.

**Comment by kingoleg** [comment]
Thanks, I was able to install it.

Does it stable enough to stay on the snapshot site?

**Comment by kingoleg** [comment]
Hehe.

But, I have editor support only now:
In my *.feature file I have following warning:

Multiple markers at this line
- Step definitions detection works only when the project is configured as cucumber project.
- 189 changed lines

Even after I tried to convert the project to cucumber one

**Comment by laeubi** [comment]
Try to perform a clean on the project.

**Comment by qvdk** [comment]
Thanks for your feedback !

You must convert your project as a cucumber project. 
Right click on your project from the Project Explorer > Configure > Convert as Cucumber Project.

The snapshot comes without any warranty. It is automatically updated on each new contribution.

**Comment by kingoleg** [comment]
Hi, 

"clean on the project." - done.

Still it doesn't work as excepted. For example, in *.feature file F3 does not open related step

**Comment by qvdk** [comment]
> You must convert your project as a cucumber project.
> Right click on your project from the Project Explorer > Configure > Convert as Cucumber Project.

**Comment by qvdk** [comment]
This is required to enable step definitions detection.

**Comment by kingoleg** [comment]
I clicked "Convert as Cucumber Project." several times for the project.

**Comment by qvdk** [comment]
Could you check if your project builds correctly ? Is it a java project ? Does you have Project > `Build automatically` enabled ?

**Comment by kingoleg** [comment]
Yes, it's java maven project. The Build automatically is turned on.

.project contains

	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
		<nature>org.eclipse.m2e.core.maven2Nature</nature>
		<nature>org.eclipse.wst.common.project.facet.core.nature</nature>
		<nature>cucumber.eclipse.nature</nature>
	</natures>

**Comment by qvdk** [comment]
With `Convert as Cucumber Project`, you should have the `cucumber.eclipse.nature` with its builders `cucumber.eclipse.builder.stepdefinition` and `cucumber.eclipse.builder.gherkin`.

Do you have errors in your logs when trying to convert ?

**Comment by kingoleg** [comment]
There is no error log when I tried  to convert it again.

I dropped cucumber.eclipse.nature from .project, refreshed the project in eclipse, converted the project to cucumber project and now I can see the builders you mentioned.

Now F3 works on *.feature! 

Thanks!

**Comment by mohanaraosv** [comment]
Details : 
Eclipse 2019-06  
cucumber version 4.7.0 
Detecting glue code is working only with following deprecated annotations
```
import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
```
and not working with the following new annotations 
```
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
```
Please suggest what could be the problem

**Comment by qvdk** [comment]
@mohanaraosv the annotations from the package `io.cucumber.java` comes from the next version of cucumber. This one is not yet supported by the plugin. See #368

**Comment by jeevan1987cool** [comment]
> Thanks for your feedback !
> 
> You must convert your project as a cucumber project.
> Right click on your project from the Project Explorer > Configure > Convert as Cucumber Project.
> 
> The snapshot comes without any warranty. It is automatically updated on each new contribution.

This worked for me!!
