### ISSUE TITLE
Provide a dedicated update site to use Cucumber in Eclipse environment

### ISSUE THREAD

**Issue by echebbi** [cucumber/cucumber-eclipse#361]
I am currently using Cucumber to test Eclipse plug-ins.

I don't know if that depends on you but it would be really convenient to dispose of an official update site that would provide Cucumber JAR as OSGi bundles (just as [Orbit](https://download.eclipse.org/tools/orbit/downloads/) does).

Moreover, the `Cucumber` JUnit runner cannot be used as it is within an OSGi environment (mainly because it does not handle Eclipse-specific schemes such as `bundleresource://`) and I had to tailor it in order to be able to run my tests as plug-in tests. Providing an official runner would be helpful for anyone willing to develop Eclipse plug-ins.

**Comment by laeubi** [comment]
This is more an issue with cucumber-core/jvm/... this project is just for providing IDE integration.

**Comment by echebbi** [comment]
That's what I thought. However, since you already package Cucumber's JAR and are familiar with Eclipse stuff I preferred to ask here first.

I will submit a new issue to the cucumber-jvm repo, then; maybe that the more convenient solution will be to create a dedicated repo for OSGi integration?

**Comment by laeubi** [comment]
See https://läubisoft.gmbh/en/articles/using-maven-artifacts-in-pde-rcp-and-tycho-builds/ how to use maven artifacts in eclipse. This will also be the way the 2.x. line will consume the cucumber releases.
