### ISSUE TITLE
Unable to Install Cucumber for Eclipse Plugin (2019-03 R Package)

### ISSUE THREAD

**Issue by Vimal-N** [cucumber/cucumber-eclipse#364]
Cucumber Eclipse Plugin not compatible with Eclipse 2019-03 R Package versions. 

![2019-03 installation Error](https://user-images.githubusercontent.com/29984601/57783650-806d6580-76fc-11e9-8913-8eec78404b78.png)

**Comment by cailliaud** [comment]
Same issue trying to install the plugin on Eclipse :
Version: 2019-03 (4.11.0)
Build id: 20190314-1200

**Comment by cbaldan** [comment]
@cailliaud did you manage to install anything from that repo? It says 
> Not available yet.

I was able to install downloading the latest Snapshot zip to my PC.

**Comment by skumardgl3** [comment]
I think cucumber can be installed in following Eclipse versions only:
Eclipse Versions: 
2018-09 (4.9), Photon (4.8), Oxygen (4.7), Neon (4.6), Mars (4.5), Luna (4.4), Kepler (4.3), Juno (4.2, 3.8), Previous to Juno (<=4.1)

I have learned this in the hard way. Hope it helps

**Comment by cailliaud** [comment]
@cbaldan even if you have a 404 on the website it works on eclipse : 

![image](https://user-images.githubusercontent.com/19285360/57944654-f843b780-78d7-11e9-9bc0-d96f69ef44ab.png)

**Comment by Vimal-N** [comment]
@cailliaud @cbaldan I tried snapshot approach but Eclipse for some reason wasn't able to get the snapshot downloaded. So, I ended up downloading 2018 version of eclipse instead to get cucumber plugin in.

**Comment by nitind** [comment]
The **Marketplace entry itself** needs to be updated to list 2019-03 (and now 2019-06) as compatible versions.

**Comment by girijant** [comment]
Updated in the Eclipse-Marketplace for the Supported Eclipse Release versions :
2019-06 (4.12) and 2019-03 (4.11).

Thanks,
Girija

**Comment by girijant** [comment]
@Vimal-N @cailliaud @cbaldan @nitind 
I recently updated our [**Eclipse-Marketplace**](https://marketplace.eclipse.org/content/cucumber-eclipse-plugin) based on the Plugin's Snapshot version-1.0.0 as below:
- Updated Marketplace with the plugin's installation site with **https://cucumber.github.io/cucumber-eclipse-update-site-snapshot/** for installing the most stable **SNAPSHOT** version '1.0.0.202001082311'  from your Eclipse-IDE.
- Updated for the below **Supported Eclipse Release versions** to avoid the incompatibilty issue:
     - 2020-03 (4.15)
     - 2019-12 (4.14)
- This plugin's snapshot version(1.0.0.202001082311) can be installed d**irectly from your Eclipse-IDE's Menu, Help > Eclipse Marketplace > Find: Cucumber > Select 'Cucumber Eclipse Plugin' >Install.**
![Cucumber_EclipseMarketplace-Window](https://user-images.githubusercontent.com/17194046/74534484-d6a45900-4f59-11ea-90fc-cbd29a3a4e1b.PNG)
    - You can skip the manual installation from the:Help > Install New software > Repo-url
- Tested with the latest Eclipe Version:2019-09-R and this plugin (version 1.0.0) is successfully installed from the Eclipse-IDE.

Please install/update the plugin from your Eclipse-IDE and let me know your feedback. As this is fixed so closing it.

Thanks,
~Girija

**Comment by priyansh90** [comment]
Hi @girijant - I'm using Eclipse Mars.2, Build id: 20160218-0600
Not able to install cucumber eclipse plugin, it throws an error - Unable to read repository at https://cucumber.github.io/cucumber-
Attaching the screenshot for your reference -
![cucumber_plugin](https://user-images.githubusercontent.com/17599282/95195467-335bc900-07f4-11eb-96fd-b6270274b086.png)

**Comment by nitind** [comment]
@priyansh90 GitHub now requires the TLS v1.2 protocol be used when connecting to it by https. Older Java runtimes may not support that properly, so you will have to use a newer one. Your release of Eclipse is also more than 4 years old and has been 
unsupported for a long time. Please update it as well.
