### ISSUE TITLE
When open feature file, Eclipse display Problem Occured

### ISSUE THREAD

**Issue by xiajikaluli** [cucumber/cucumber-eclipse#366]
An internal error occurred during: "Scanning for step definitions". java.lang.NullPointerException
![image](https://user-images.githubusercontent.com/8199375/58846684-9f836580-86b2-11e9-9703-1d70293cb3e5.png)

**Comment by xiajikaluli** [comment]
I write wrong language info，zh-CN is correct ,but mine is zh_CN

**Comment by qvdk** [comment]
Thanks for your feedback.
This error should not be thrown and a language parsing error should be displayed in the error view.
