### ISSUE TITLE
Eclipse doesn't find step definitions in jar files

### ISSUE THREAD

**Issue by bobpaige** [cucumber/cucumber-eclipse#367]
I understand this feature was added previously, but it is not working for me today.

I am running Spring Tool Suite 4
Version 4.2.1.RELEASE
Build Id: 201904170946

I had previously installed eclipse-cucumber via the update site, but now that it is available in the Marketplace, I uninstalled it and re-installed via the Marketplace. It was the same version anyway.

I started with the step definitions in the same project. I then packaged them in a .jar file and added them to the classpath in another project, but that new project does not find the step definitions.

I have confirmed (Referenced Libraries -> Library name -> package) that it is on the classpath.

I have tried adding the specific package name to the Window -> Preferences -> Cucumber -> Plugin Settings under "Only match steps from specific package and sub-packages".

I have a simple JUnit class that _does_ find the steps and runs fine:
```
@RunWith(Cucumber.class)
@CucumberOptions(glue = {"com.myproject.mysteps"}, plugin = { "pretty", "html:target/cucumber", "junit:target/cucumber.xml" })
public class CucumberRunner {
}
```
It is only when I'm editing a .feature file or trying to execute scenarios from the editor that it fails.

I noticed that if I exclude the `glue = {}` option in the JUnit class that it fails there as well.

**Comment by bobpaige** [comment]
I tried a few more things and the situation is getting worse.

First, I upgraded cucumber-java to the latest version (was at 2.0.1, upgraded to 4.4.0). 
Second, I reinstalled STS and the eclipse-cucumber plugin.

Now my original project (where the step definitions are discreet classes in src/main/java) no longer can find the step definitions.

It is important to note that everything runs fine from the commandline and from JUnit. It is only the eclipse-cucumber plugin having trouble finding anything.

Is there some other configuration open I can set in eclipse-cucumber to tell it where my step definitions are? Something I'm missing, or has changed?

**Comment by qvdk** [comment]
Hi, 
Could you provide a sample projet where the bug is reproductible on GitHub please ?
Can you confirm your test project has the Cucumber project nature ?
Thank you for your feedback.

**Comment by bobpaige** [comment]
I confirmed I don't have the Cucumber nature on my project. But after I
added it in Eclipse, the behavior has not changed.

[image: image.png]

.project file before:
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
        <name>in-cucumber</name>
        <comment></comment>
        <projects/>
        <natures>
                <nature>org.eclipse.jdt.core.javanature</nature>
        </natures>
        <buildSpec>
                <buildCommand>
                        <name>org.eclipse.jdt.core.javabuilder</name>
                        <arguments/>
                </buildCommand>
        </buildSpec>
        <linkedResources/>
        <filteredResources/>
</projectDescription>


.project file after:
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
        <name>in-cucumber</name>
        <comment></comment>
        <projects>
        </projects>
        <buildSpec>
                <buildCommand>
                        <name>org.eclipse.jdt.core.javabuilder</name>
                        <arguments>
                        </arguments>
                </buildCommand>
                <buildCommand>
                        <name>cucumber.eclipse.steps.jdt.stepsBuilder</name>
                        <arguments>
                        </arguments>
                </buildCommand>
        </buildSpec>
        <natures>
                <nature>org.eclipse.jdt.core.javanature</nature>
                <nature>cucumber.eclipse.steps.jdt.stepsNature</nature>
        </natures>
</projectDescription>

**Comment by laeubi** [comment]
please make sure to clean the project once after enable the new nature

**Comment by bobpaige** [comment]
I added this sample project today: https://github.com/bobpaige/cucumber-eclipse-with-libs

The README.md explains how to reproduce what I'm seeing.

Feel free to comment/email with suggestions. I really like the plugin and appreciate you helping me through this complication.

**Comment by qvdk** [comment]
I can't reproduce your case. After importing your sample as you described, I added the Cucumber nature from the contextual menu (right click on project) `Configure > Convert to Cucumber Project...`, then the steps are detected as expected. (cf. screencast)

Version: 2019-06 (4.12.0)
Build id: 20190614-1200

![with-libs gif](https://user-images.githubusercontent.com/6142398/60472397-04f25400-9c69-11e9-9568-875526eca522.gif)

**Comment by qvdk** [comment]
OK I reproduced the issue.
The version from the Eclipse Marketplace is not up-to-date.
Please install the latest snapshot of the plugin from our Eclipse update site as described here: https://github.com/cucumber/cucumber-eclipse-update-site-snapshot

This version will work.

@girijant Could you update the Eclipse Marketplace with the latest snapshot please ?

**Comment by bobpaige** [comment]
Thanks for the update.

I removed the copy from Eclipse Marketplace and installed from the update site. It does indeed find the definitions now, but I'm seeing two new behaviors.

The first one seems to be innocuous. After converting to a Cucumber project and cleaning the project, it creates a new "cucumber-eclipse-with-libs" directory within my directory. I tried this a couple times with variations of creating a new project, deleting it, cleaning, etc. It always happens after the clean. If I try to delete it, it immediately comes back. 

Second, when I right-click and select "Run as -> Cucumber feature", I get a "Problem Occurred" dialog with the error "Launch configuration CustomerInquiry.feature references non-existing project cucumber." I don't have any project named 'cucumber' :)

**Comment by bobpaige** [comment]
I may have tracked down this latest issue, and it is in my project not the plugin.

I had some old .class files in the Eclipse /bin directory that Eclipse was *not* removing when I cleaned the project. I had to manually delete the directory (sigh).

Thanks again for your time in tracking this down.

**Comment by qvdk** [comment]
You are welcome.
Thanks for your feedback.
