### ISSUE TITLE
Deprecated Main class cucumber.api.cli.Main

### ISSUE THREAD

**Issue by AdrianSchneble** [cucumber/cucumber-eclipse#370]
When launching my feature files using the plugin, I get a warning in the console stating "You are using deprecated Main class. Please use io.cucumber.core.cli.Main".

This has been changed just about a month ago (see https://github.com/cucumber/cucumber-jvm/pull/1670). The old class is currently a delegate to the new class, so this doesn't break anything (yet?), but the warning is a little annoying. From my perspective, this seems like a pretty easy thing to fix for someone who knows the plugin's code, but since that's not the case for me, I decided to open this issue instead.

//edit:
After a quick repo search, it looks like [this class](https://github.com/cucumber/cucumber-eclipse/blob/master/cucumber.eclipse.editor/src/main/java/cucumber/eclipse/launching/CucumberFeatureLocalApplicationLaunchConfigurationDelegate.java) is using the `CUCUMBER_API_CLI_MAIN` constant from [this class](https://github.com/cucumber/cucumber-eclipse/blob/master/cucumber.eclipse.editor/src/main/java/cucumber/eclipse/launching/CucumberFeatureLaunchConstants.java) to get the FQN for the Main class. I'm guessing updating this constant should fix the issue. However, I don't really have any experience developing eclipse plugins and since I don't want to push any changes based on guesses, I'll leave this to someone else.

**Comment by laeubi** [comment]
If we simply change this, this wil break for everyone using an older cucumber-version so it is not that easy as it seems.

**Comment by RusmanCool** [comment]
@laeubi Could you release a new Major version update that uses the latest io.cucumber pacakages? It allows to start using new features without braking the code for all users of the dependency. This is how it is done industry wise.

**Comment by a1dutch** [comment]
The way this is generally handled is you try to load the new class in the new package, if it fails with a class not found exception you load the old class.

**Comment by DraxDomax** [comment]
I am sorry, I am quite the newbie (probably shouldn't be commenting here), but if I understand correctly:
The cucumber plugin for eclipse calls the old main method (which still works).
In that case, what is the point to change the main method? (since the plugin is calling the old one anyway).
Is it in order to facilitate modernisation within other IDEs (so, for example, IntelliJ wouldn't have this warning)?
If that is so, can we expect an update to the cucumber eclipse plug that will fix this deprecated call?
(I realise the answer is: "yes, when you commit the code" but be assured that you don't want me programming your IDE!)

**Comment by mohamedelgaml** [comment]
i think this may work for you 
https://stackoverflow.com/questions/57177823/exception-in-thread-main-after-updating-cucumber-version  
or if you solve it can you share the solution?

**Comment by shahnawazm786** [comment]
Feature: features to test login functionality
  
  
  Scenario : Check login is successful with valid credential
  
  Given user is on login page
  When user enters username and password
  And clicks on login button
  Then user is navigated to the home page

Above is mu content of feature file and i am getting following message.

**Sep 15, 2020 8:27:02 PM cucumber.api.cli.Main run
WARNING: You are using deprecated Main class. Please use io.cucumber.core.cli.Main

0 Scenarios
0 Steps
0m0.130s**

**Comment by allanpfreitas** [comment]
This will be fixed ?

**Comment by chetanSrajiv** [comment]
it worked for me when i downgraded my testng dependency version from 7.4.0 to 7.1.0. try adding this dependency to your pom.xml

		
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.1.0</version>
		</dependency>

**Comment by laeubi** [comment]
> This will be fixed ?

No, at least not in the "current" version, as this is only a warning it also does not harm much.

Beside that, there is currently a major refactoring going on for a next generation plugin that will fix this and many other issues in a more convenient way that it is done today. 

If one likes to help with testing/feedback check out the https://github.com/cucumber/cucumber-eclipse/tree/cucumber6 branch, compile it and install the resulting into at least Eclipse 2021-03 Eclipse.

**Comment by laeubi** [comment]
We are currently developing a new version of the cucumber-plugin with improved support for more recent cucumber versions, if you like try out the following update-site (please uninstall the old plugin before):
https://cucumber.github.io/cucumber-eclipse/update-site/main/

**Comment by omprakashchavan01** [comment]
@laeubi getting "Page not found" for the update-site link.

**Comment by laeubi** [comment]
@omprakashchavan01 the updatesite can only be used in eclipse (`Help>Install new Software`)
