### ISSUE TITLE
cucumber-eclipse plugin does not support Cucumber 5

### ISSUE THREAD

**Issue by ralphkar** [cucumber/cucumber-eclipse#372]
I am currently using the current develop version of Cucumber 5, but the cucumber-eclipse plugin does no longer seem to be able to match the steps with the Java code.
To be honest... this is not only since Cucumber 5 but is also a problem with the latest versions of Cucumber 4 (e.g. 4.7.1)

**Comment by trzimar** [comment]
Might be connected with issue #368

**Comment by laeubi** [comment]
This is a duplicate of #368

Just wondering: Why do you use Cucumber 5 development, what are the new features/bugfixes that requires this?
We are currently working on a way to handle over the parsing to cucumber runtime itself, but this will take some time, because most of the people here are working in their free time for this.

If your company is specially interested in cucumber-5 support for the eclipse part, feel free to contact me directly and I might can offer them paid support to speed up development, all my current customers are only using cucumber-4 atm.

**Comment by ralphkar** [comment]
Ok, it's a duplicate...

Just as info: Yes, we are currently using Cucumber 5 development, because it allows us to run different tests with different DI configurations. Our app has some plugin functionality and this way we can configure differently for plugins.
AFAIK Cucumber 5 might be released in september. I have absolutely no experience in developing Eclipse plugins so I guess I'll just have to wait for the cucumber-eclipse to catch up.

**Comment by ralphkar** [comment]
Duplicate of #368

**Comment by laeubi** [comment]
@ralphkar 'different tests with different DI configurations' this is another feature that is not implemented yet and probably would require even more work since currently cucumber eclipse plugin works on a project level.

**Comment by ralphkar** [comment]
Ok. I see. I am not aware of all the capabilities of cucumber-eclipse. We
are not running any tests through the plugin, but rather use it to support
us in the IDE. We like the syntax highlighting and the capability to find
the source code for a test step. This is about it. And for that different
DI configurations at test runtime (see: object factory) should not be
relevant.

Greetings,
Ralph

Am Fr., 2. Aug. 2019 um 09:01 Uhr schrieb Christoph Läubrich <
notifications@github.com>:

**Comment by laeubi** [comment]
This depends, if you use TypeFactories, these are found through the ObjectFactory and currently the latest snapshot version of the plugin only support one per classpath as cucumber cli.

**Comment by ralphkar** [comment]
True, this could be an issue.
But not in our setup. We do not vary the DI configuration that provides the
Cucumber stuff, but only the one that varies our application.
We run it through different JUnit tests. Each of the test uses
@CucumberOptions to specify a different object factory.

Am Fr., 2. Aug. 2019 um 09:37 Uhr schrieb Christoph Läubrich <
notifications@github.com>:
