### ISSUE TITLE
Cucumber-eclipse plugin does not identify step definitions when io.cucumber.java.en annotations are used

### ISSUE THREAD

**Issue by Shiridish-BK** [cucumber/cucumber-eclipse#373]
I have a maven project with cucumber dependencies (v4.6.0) and I have installed cucumber-eclipse plugin v0.0.23.2018 in my Eclipse (v2019-06 (4.12.0)).

I see that the step definitions are not identified by the plugin in this project. I am not sure what I have done wrong. 

FYI, I have downloaded the cucumber-java-skeleton project and I see that the step definitions are identified there by the plugin, so its likely not an issue with plugin/eclipse setup but an issue in my project setup. 

Please see below screen shot of my package structure:
![image](https://user-images.githubusercontent.com/53466830/64262584-ef8cf500-cf4b-11e9-938a-9c226dc35d85.png)

----------------------------------------------------------------------------------------------------
UPDATE: I found that when I use io.cucumber.java.en annotations, it doesn't identify the step definitions. However if I use the deprecated cucumber.api.java.en annotations, it identifies. Is this limitation of the plugin that it doesn't work with the cucumber version 4.6.0?

**Comment by mpkorstanje** [comment]
Check https://github.com/cucumber/cucumber-eclipse/pull/369 you'll have to use the snapshot update site until this has been released.

**Comment by Shiridish-BK** [comment]
Oh OK. It would have been nice if the cucumber version that the officially released plugin supports/uses is mentioned in the documentation to avoid this confusion. In case if this is already there, kindly point me to URL.

**Comment by mpkorstanje** [comment]
It most certainly would be! However Cucumber is an open source project and moves at the speed of its mostly unpaid volunteer contributors. But that does mean you can easily make improvements where necessary. 

Feel free to add a brief note to the release notes for 4.5.0 to inform people how to get the most recent snapshot. You can find Cucumber-JVMs change log here: https://github.com/cucumber/cucumber-jvm/blob/master/CHANGELOG.md#450-2019-06-30

**Comment by qvdk** [comment]
For more information on how to automatically update eclipse with the latest snapshot of the cucumber eclipse plugin see : https://github.com/cucumber/cucumber-eclipse#follow-the-latest-snapshot

**Comment by qvdk** [comment]
@Shiridish-BK can you confirm if the latest snapshot solves your issue ?

**Comment by Shiridish-BK** [comment]
@mpkorstanje I added a note to the release notes for 4.5.0 and created a pull request.

**Comment by Shiridish-BK** [comment]
@qvdk Yes, I tested the latest snapshot and it works fine. Thank you.
