### ISSUE TITLE
Gherkin syntax highlighting does not recognise leading strings

### ISSUE THREAD

**Issue by PyvesB** [cucumber/cucumber-eclipse#378]
Hello there!

When a string is used as the first element in a step, syntax highlighting does not work. For example:
![Screenshot 2019-11-25 at 16 54 15](https://user-images.githubusercontent.com/10694593/69560840-47b02200-0fa4-11ea-8fd6-1811c6c07fbf.png)

Other built-in types such as integers don't seem to be affected.

Thanks in advance for looking into this!

**Comment by qvdk** [comment]
Please can you check the latest [snapshot 1.0.0-20191126220948.102](https://github.com/cucumber/cucumber-eclipse/releases/tag/1.0.0-20191126220948.102)
If you installed the plugin thanks to the snapshot update site, Eclipse will suggest you the update automatically.

**Comment by PyvesB** [comment]
Just installed the latest snapshot: I confirm this is now working!
