### ISSUE TITLE
this plugin not fund all java step

### ISSUE THREAD

**Issue by sgrillon14** [cucumber/cucumber-eclipse#382]
I use cucumber-jvm 4.7.1 and Spring Tool Suite 4-4.0.1

My java class:

```
import io.cucumber.java.en.And;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import io.cucumber.java.fr.Alors;

public class CamundaSteps  { ...

   @Then("The CAMUNDA home page is displayed")
    public void checkCamundaHomePage() {
        ...
    }

}
```

My feature file:

```
@000
Feature: 000

  Scenario Outline:  Issuance

    Given The CAMUNDA home page is displayed

```

In feature file, all my steps are yellow color.

**Comment by qvdk** [comment]
Hello, 

Could you provide your version of cucumber eclipse plugin ?

**Comment by sgrillon14** [comment]
Cucumber Eclipse Plugin 0.0.23.201811220126

**Comment by qvdk** [comment]
Could you retry with the latest version of the plugin thanks to the dedicated update site please : https://github.com/cucumber/cucumber-eclipse-update-site-snapshot

**Comment by qvdk** [comment]
They are a bug with the Scneario Outline. 
The bug affects the latest 1.0.0-SNAPSHOT too.
