### ISSUE TITLE
.feature file is not linked to step definition in eclipse

### ISSUE THREAD

**Issue by rakeshbg005** [cucumber/cucumber-eclipse#383]
HI Team,

As shown in the screen shot cucumber test scripts are running, but .feature file is not linked to step definition in eclipse when I try to do CTRL+click and F3, day by day step definition class files are going increasing in development and we need to navigate from .feature file to step definition methods

Please help me in resolving this issue 

![Eclipse Marketplace 2019-12-18 12-46-46](https://user-images.githubusercontent.com/21195831/71064906-2d79f600-2196-11ea-8968-d68c929f4fb8.png)
![AtlasBPNov28721 - Eclipse IDE 2019-12-18 12-35-30](https://user-images.githubusercontent.com/21195831/71064907-2e128c80-2196-11ea-9aed-ab86c24b756f.png)
![src:test:java:StepDefinition:AtlaslogIn java - Eclipse IDE 2019-12-18 12-54-26](https://user-images.githubusercontent.com/21195831/71064908-2e128c80-2196-11ea-94a3-b62a740ce28d.png)

Thanks in Advance 
Rakesh

**Comment by mohanaraosv** [comment]
I'm not sure which Eclipse version you are using but try as specified in the [https://github.com/cucumber/cucumber-eclipse/issues/364#issuecomment-493530025](here)

**Comment by qvdk** [comment]
Hello, 
First, I hope you an happy new year :)
To solve your issue, [install the latest snapshot](https://github.com/cucumber/cucumber-eclipse#follow-the-latest-snapshot).

**Comment by rakeshgo** [comment]
Eclipse Version: 2018-09(4.9.0)  
Build Id: 20180917 -1800  

Cucumber plug-in version :
![image](https://user-images.githubusercontent.com/19202009/72071326-89f1b080-3311-11ea-960b-b969ad6b9fd5.png)

Maven dependency :

<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>4.7.1</version>
		</dependency>
		<dependency>
		    <groupId>io.cucumber</groupId>
		    <artifactId>cucumber-testng</artifactId>
		    <version>4.7.1</version>
		</dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>1.2.5</version>
        </dependency>

**Comment by rakeshgo** [comment]
> Hello,
> First, I hope you an happy new year :)

belated wishes wish you a happy new year bro

**Comment by rakeshgo** [comment]
![image](https://user-images.githubusercontent.com/19202009/72072306-a8f14200-3313-11ea-8241-8bd64a4ad08a.png)

**Comment by qvdk** [comment]
So I confirm you issue will be solved by [installing the latest snapshot](https://github.com/cucumber/cucumber-eclipse-update-site-snapshot).

You should obtain the version 1.0.0-SNAPSHOT

When installed, convert your project as Cucumber project : Right click on your project to open the contextual menu > `Configure` > `Convert as Cucumber project...`

**Comment by rakeshgo** [comment]
I have installed latest snapshot after that Convert as Cucumber project... option is not displaying 
![image](https://user-images.githubusercontent.com/19202009/72076508-a1359b80-331b-11ea-8516-f8998fde6128.png)

**Comment by rakeshgo** [comment]
Thanks, bro it's working now

**Comment by rakeshgo** [comment]
I guess we can close this ticket
