### ISSUE TITLE
eclipse cucumber offline plugin link not found

### ISSUE THREAD

**Issue by Akhilkr96** [cucumber/cucumber-eclipse#384]
plz share latest version offline link

**Comment by qvdk** [comment]
Offline installations are provided for each version in the [release section](https://github.com/cucumber/cucumber-eclipse/releases).
Assets > cucumber-eclipse-plugin-1.0.0-SNAPSHOT.zip

**Comment by Akhilkr96** [comment]
Thanks for the reply. When I tried to add this in environment , which wont have network access , offline version not installing ,plz help.


Cannot complete the install because one or more required items could not be found.
  Software being installed: Cucumber Eclipse 1.0.0.201911262209 (cucumber.eclipse.feature.feature.group 1.0.0.201911262209)
  Missing requirement: Cucumber Editor 1.0.0.201911262209 (cucumber.eclipse.editor 1.0.0.201911262209) requires 'osgi.bundle; org.eclipse.pde.ui 3.5.0' but it could not be found
  Cannot satisfy dependency:
    From: Cucumber Eclipse 1.0.0.201911262209 (cucumber.eclipse.feature.feature.group 1.0.0.201911262209)
    To: org.eclipse.equinox.p2.iu; cucumber.eclipse.editor [1.0.0.201911262209,1.0.0.201911262209]
