### ISSUE TITLE
Cucumber plug in not installed in offline mode which have no internet access

### ISSUE THREAD

**Issue by Akhilkr96** [cucumber/cucumber-eclipse#385]
When I tried to add  cucumber plug in restricted , which wont have network access , offline version not installing and throwing error given below ,plz help.

Cannot complete the install because one or more required items could not be found.
Software being installed: Cucumber Eclipse 1.0.0.201911262209 (cucumber.eclipse.feature.feature.group 1.0.0.201911262209)
Missing requirement: Cucumber Editor 1.0.0.201911262209 (cucumber.eclipse.editor 1.0.0.201911262209) requires 'osgi.bundle; org.eclipse.pde.ui 3.5.0' but it could not be found
Cannot satisfy dependency:
From: Cucumber Eclipse 1.0.0.201911262209 (cucumber.eclipse.feature.feature.group 1.0.0.201911262209)
To: org.eclipse.equinox.p2.iu; cucumber.eclipse.editor [1.0.0.201911262209,1.0.0.201911262209]

**Comment by Akhilkr96** [comment]
[my.log](https://github.com/cucumber/cucumber-eclipse/files/3995134/my.log)
please find local eclipse log while trying to install

**Comment by laeubi** [comment]
Your eclipse is not properly configured for offline/proxy access.
