### ISSUE TITLE
Not able to navigate from feature file step to stepdefination

### ISSUE THREAD

**Issue by stephenws** [cucumber/cucumber-eclipse#388]
I am using Eclipse Oxygen.3a Release (4.7.3a) and installed Eclipse-cucumber plugin.
I have written step definition wrt to feature file scenario 
but still in I am not able to navigate from feature file to step definition.
also steps are highlighted with yellow colour

Step def path : src/test/java/com/test/stepDefinations/test.java
Feature File Path : src/test/resources/Features/test.feature
Cucumber version used: 4.7.4
 
<img width="368" alt="Screenshot 2020-01-23 at 14 24 25" src="https://user-images.githubusercontent.com/26320996/72988280-3fc9fe00-3dec-11ea-88bc-b0e0a96619b2.png">
<img width="460" alt="Screenshot 2020-01-23 at 14 25 29" src="https://user-images.githubusercontent.com/26320996/72988295-46587580-3dec-11ea-8d64-f93b97a0514a.png">

**Comment by qvdk** [comment]
Hello, 

Could you check you are using the latest version of the plugin ?
See https://github.com/cucumber/cucumber-eclipse-update-site-snapshot

Then, ensure you configure the project to use cucumber plugin. From the contextual menu from your project (right clic on your project) > `Configure` > `Convert as cucumber...`

Does it solve your issue ?

**Comment by stephenws** [comment]
Yeah thats work for me, Thank you..

**Comment by akshayshinde19** [comment]
Thanks it worked for me as well
