### ISSUE TITLE
Getting warning in the feature file -"Step does not have a matching glue code

### ISSUE THREAD

**Issue by srikant-mvs** [cucumber/cucumber-eclipse#389]
I am using SpringToolSuite version 3.9.8 and have installed the latest cucumber eclipse plugin today.
I am seeing warnings messages in my feature file.
Below are the setup of my path
1. Feature file : /src/test/resources/
2. Runner file : src/test/java with @CucumberOptions(features="src/test/resources/features")
3. Step file : src/test/java

Step 'I want to do operation "/Operation"' does not have a matching glue code

![image](https://user-images.githubusercontent.com/18280467/73739105-eb0c7880-4745-11ea-92d8-9f59b6de735d.png)

**Comment by qvdk** [comment]
Hello @srikant-mvs , 

Could you try the solution suggested in the FAQ please ?
https://github.com/cucumber/cucumber-eclipse/wiki/FAQ#my-step-definitions-are-not-detected-and-my-steps-from-my-feature-file-is-highlight-in-yellow

Does it solve your issue ?

**Comment by srikant-mvs** [comment]
Thanks, that fixed the issue. I am also able to navigate to the step method.
