### ISSUE TITLE
Cucumber Building(sleeping) thread will block other tasks to startup

### ISSUE THREAD

**Issue by alan-denight** [cucumber/cucumber-eclipse#390]
Hi Cucumber plugin team, 

thanks for this great plugin, it helped a lot to simply the BBD development process.

I have a issue when editing the feature file, when I change some context in the feature file, then  Cucumber Building(sleeping) thread will block other tasks to startup, if I removed the Cucumber builder from the project, then all the functions work properly.  could you please have a look at this issue? 

I am using the Eclipse Platform Version: 4.14.0.v20191210-0610

 

Cheers,

Alan

**Comment by laeubi** [comment]
Cucumber builder won't be needed anymore in the 2.x line
