### ISSUE TITLE
The step definition using annotations from `io.cucumber` located in the classpath are not detected

### ISSUE THREAD

**Issue by qvdk** [cucumber/cucumber-eclipse#391]
it's already better, the plugin finds the steps that are in the project. I still have a problem, **it can't find the steps that are in a dependency (Maven)** that contains generic steps.

**Reproduce my problem:**

* run this Maven command: `mvn archetype:generate -B -DarchetypeGroupId=com.github.noraui -DarchetypeArtifactId=noraui-archetype -DarchetypeVersion=4.0.0.0 -DgroupId=com.your.company -DartifactId=robot -Dversion=0.0.1-SNAPSHOT -DinteractiveMode=false`

* Import robot project generated in Eclipse

* I added the cucumber nature to my project. Open the contextual menu from my project - right click - Configure > Convert as cucumber project... A cucumber icon will appears on my project.

* run project is OK but the plugin can't find the steps that are in a dependency (Maven)

![image](https://user-images.githubusercontent.com/5530550/73822766-1a2ef280-47f7-11ea-8aa9-7ec682bc9485.png)

I try add package in Cucumber plugin configuration but do not work:

![image](https://user-images.githubusercontent.com/5530550/73823536-c1f8f000-47f8-11ea-95ab-47407014dd82.png)

_Originally posted by @sgrillon14 in https://github.com/cucumber/cucumber-eclipse/pull/369#issuecomment-582289110_

**Comment by sgrillon14** [comment]
bug fix, :)
