### ISSUE TITLE
Whens, Thens ... are marked with no matching glue code

### ISSUE THREAD

**Issue by htrost** [cucumber/cucumber-eclipse#393]
When we are using the multiple annotations _Whens__, _Thens_, _Givens_ and so on the plugin marks them as "does not have a matching glue code" in the fetaure files. It looks like that the plugin is not able to handle the "multiple" annotations.

For example

@Given("Logged into app")

works fine and is recognized by the plugin within the feature files. But this one

@Givens({
@Given("Logged into app")
})

is not recognized but it is working when we are executing the test.

**Comment by maeichris** [comment]
You did not mention the version you were running.

The latest official version was 0.0.23 from 2018-11.  It is available at this update site:

https://cucumber.github.io/cucumber-eclipse/update-site

You can get an unreleased snapshot version (1.0.0.202012131300) from 2020-12 from this update site:

https://cucumber.github.io/cucumber-eclipse-update-site-snapshot

**Comment by laeubi** [comment]
the parsing is done using cucumber-jvm in 2.x line please retest and report if the issue persits.
