### ISSUE TITLE
Step Defination is coming up in cucumber on press Ctrl+ in step defination and cannot navigate to methods

### ISSUE THREAD

**Issue by PIYUSHJAIN1984** [cucumber/cucumber-eclipse#395]
Step Defination is coming up in cucumber on press Ctrl+ in feature file  and cannot navigate to methods

**Comment by PIYUSHJAIN1984** [comment]
<img width="576" alt="cucumber" src="https://user-images.githubusercontent.com/38496131/77241323-68b51680-6c16-11ea-9c98-f5ed99d53e32.png">
<img width="576" alt="cucumber" src="https://user-images.githubusercontent.com/38496131/77241330-808c9a80-6c16-11ea-8f9f-89a3071da2ea.png">
![Uploading eclipse.PNG…]()

**Comment by PIYUSHJAIN1984** [comment]
<img width="455" alt="eclipse" src="https://user-images.githubusercontent.com/38496131/77241332-94380100-6c16-11ea-8eef-9dd42811d1c9.PNG">

**Comment by rakeshbg005** [comment]
HI Piush,

install the latest snap shot







*cucumber-eclipse-update-site-snapshot
<https://github.com/cucumber/cucumber-eclipse-update-site-snapshot>- From
Eclipse, go to menu Help > Install New software - Work with:
https://cucumber.github.io/cucumber-eclipse-update-site-snapshot
<https://cucumber.github.io/cucumber-eclipse-update-site-snapshot> - Select
the check-box for Cucumber Eclipse Plugin - Select Next as per the
instruction shown during installation. - Restart your Eclipse after
completion of instruction.Right click on the project and convert into
cucumber project *

**Comment by PIYUSHJAIN1984** [comment]
ISSUE RESOLVED. iNSTALLED THROUGH HELP IN ECLIPSE - CUCUMBER PLUGIN
