### ISSUE TITLE
Which update site to use?

### ISSUE THREAD

**Issue by LorenzoBettini** [cucumber/cucumber-eclipse#396]
Hi

on the website, http://cucumber.github.io/cucumber-eclipse/, the update site for stable release is https://cucumber.github.io/cucumber-eclipse/update-site, which contains "Cucumber Eclipse Feature", "cucumber.eclipse.feature.feature.group", version 0.0.23.201811220126. Then, on the Market Place, https://marketplace.eclipse.org/comment/6536#comment-6536, the update site https://cucumber.github.io/cucumber-eclipse-update-site is mentioned, containing "Cucumber Eclipse", version 1.0.0. So is this the new stable update site?

Thanks in advance

**Comment by qvdk** [comment]
Hi, 

The Eclipse marketplace is linked with https://cucumber.github.io/cucumber-eclipse-update-site
So, with the Eclipse Marketplace or this previous update site, you will have the same version.

If you want to use the latest snapshot, you can use https://cucumber.github.io/cucumber-eclipse-update-site-snapshot

**Comment by LorenzoBettini** [comment]
Sorry in my original issue report I made a mistake. The update site reported on the web site is https://cucumber.github.io/cucumber-eclipse/update-site which is not the correct one.
That's what I meant

**Comment by girijant** [comment]
@LorenzoBettini,
Here is the Eclipse-Market place link of cucumber-eclipse plugin:
https://marketplace.eclipse.org/content/cucumber-eclipse-plugin

**Comment by LorenzoBettini** [comment]
@girijant the issue is about update site, not market place

**Comment by laeubi** [comment]
@LorenzoBettini this are the current update-sites:

Unstable-Latest: https://cucumber.github.io/cucumber-eclipse/update-site/main/
Releases: https://cucumber.github.io/cucumber-eclipse/update-site/

If you find any inconsistencies please open a PR to fix/update.
