### ISSUE TITLE
Cucumber 5 Navigation to step definition does not work with Cucumber JVM spring boot project 

### ISSUE THREAD

**Issue by Sulbh** [cucumber/cucumber-eclipse#397]
I have a spring boot project which has 2.2.6, and cucumber version 5.6 
after updating plugin navigation to step definition still do not work.

**Comment by Sulbh** [comment]
Sprig boot version 2.2.6 and Cucumber version 5.6 all other dependencies are using these two versions

**Comment by acooper267** [comment]
For cucumber 5 I'm using spring 5. I saw issues when using a old spring version. I'm using Cucumber Eclipse plugin version 1.0.0.202003111437 
What version of cucumber-eclipse plugin are you using?

<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
			<version>5.2.2.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>5.2.2.RELEASE</version>
		</dependency>
<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>5.4.0</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>5.4.0</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-spring</artifactId>
			<version>5.4.0</version>
		</dependency>

**Comment by Sulbh** [comment]
I am using a spring boot and below is the latest available version

<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.6.RELEASE</version>


 for other dependencies I am not specifying any version for ex 
cucumber.version=5.6
Sprig boot version 2.2.6

<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-spring</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

**Comment by laeubi** [comment]
We have reworked the whole parsing/navigation in the 2.x line please retest there and report if the issue persits.
