### ISSUE TITLE
Error when installing cucumber-eclipse-1.0.0.202003111437

### ISSUE THREAD

**Issue by acooper267** [cucumber/cucumber-eclipse#398]
How do i resolve this error?

Software being installed: Cucumber Eclipse 1.0.0.202003111437 (cucumber.eclipse.feature.feature.group 1.0.0.202003111437)
  Missing requirement: Cucumber Java Backend 1.0.0.202003111437 (cucumber.eclipse.backends.java 1.0.0.202003111437) requires 'bundle org.eclipse.jdt.core 3.11.2' but it could not be found
  Cannot satisfy dependency:
    From: Cucumber Eclipse 1.0.0.202003111437 (cucumber.eclipse.feature.feature.group 1.0.0.202003111437)
    To: cucumber.eclipse.backends.java [1.0.0.202003111437]

**Comment by acooper267** [comment]
I install Spring Tool Suite 4 and this issue went away, but the plugin "find steps" feature doesn't work. 
Version: 4.5.1.RELEASE
Build Id: 202001211336

**Comment by Ashkm77** [comment]
The older "Cucumber Eclipse Plugin 1.0.0.202001082311" got installed instead of "1.0.0.202003111437" and it is working fine for me!
I'm also able to use the "Find step definition" feature. I'm using Cucumber version 5.5.0.

**Comment by laeubi** [comment]
Please try the new 2.x version and report if the issue persits.
