### ISSUE TITLE
Unable to install the Cucumber Eclipse Plugin 1.0.0.202003111437 for Eclipse 4.15

### ISSUE THREAD

**Issue by Ashkm77** [cucumber/cucumber-eclipse#401]
Getting error as:
Cannot complete the install because one or more required items could not be found.   Software being installed: Cucumber Eclipse 1.0.0.202003111437 (cucumber.eclipse.feature.feature.group 1.0.0.202003111437)   Missing requirement: Cucumber Editor 1.0.0.202003111437 (cucumber.eclipse.editor 1.0.0.202003111437) requires 'osgi.bundle; org.eclipse.pde.ui 3.5.0' but it could not be found   Cannot satisfy dependency:     From: Cucumber Eclipse 1.0.0.202003111437 (cucumber.eclipse.feature.feature.group 1.0.0.202003111437)     To: org.eclipse.equinox.p2.iu; cucumber.eclipse.editor [1.0.0.202003111437,1.0.0.202003111437]

**Comment by acooper267** [comment]
This sounds like my error https://github.com/cucumber/cucumber-eclipse/issues/398

**Comment by Ashkm77** [comment]
Yes, it is kind of similar. However, it is fixed for me now. So closing.
When I searched, it shown me the result as "Cucumber Eclipse Plugin 1.0.0.202001082311" and while accepting the license, it shown the version as "Cucumber Eclipse 1.0.0.202003111437", however the older version "Cucumber Eclipse Plugin 1.0.0.202001082311" got installed and it is working fine for me! 
I'm also able to use the "Find step definition" feature. I'm using Cucumber version 5.5.0.
