### ISSUE TITLE
illegal reflective access operation

### ISSUE THREAD

**Issue by cowang** [cucumber/cucumber-eclipse#404]
I have been getting the following error message for over a year. Use Windows 10 on a Surface. Just updated Eclipse to

    Version: 2020-03 (4.15.0)
    Build id: 20200313-1211

and Cucumber

    Version: 1.0.0.202003111437

And still get the warning. The problem doesn't seem to affect output in any other way, but the message gives dire warnings:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cucumber.deps.com.thoughtworks.xstream.core.util.Fields (file:/C:/Users/cowan/Documents/GitHub/TrueJ/vendor/lib/cucumber-jvm-deps-current.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of cucumber.deps.com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by cowang** [comment]
I found the following note at
<https://github.com/cucumber/cucumber-jvm/blob/40657a683bfe922a02d745a3b8fba4a54c1b4d05/CHANGELOG.md>

1.0.0.RC15 (2012-02-07)
[Java] You must use **cucumber.runtime.xstream** instead of com.thoughtworks.xstream for custom converters.

I'm not qualified to say if that is the problem.

**Comment by mpkorstanje** [comment]
You may want to consider upgrading your version of Cucumber. Note that the groupId has changed to `io.cucumber`.

**Comment by laeubi** [comment]
No feedback until now, please reopen with further details if this is still relevant for you.
