### ISSUE TITLE
Feature file showing No defination found for Given, When, Then 

### ISSUE THREAD

**Issue by ddama09** [cucumber/cucumber-eclipse#408]
Hi,
I am new to the cucumber and practicing on creating cucumber framework. I created Feature file and Step Definition file. On feature file it is showing No definition found but the methods are mentioned in Step definition file.
![image](https://user-images.githubusercontent.com/65765369/82660497-1d37dc80-9c48-11ea-9bfa-a60048bcb47b.png)
![image](https://user-images.githubusercontent.com/65765369/82660537-2de85280-9c48-11ea-93c4-41ee73663d12.png)
 
In POM is used below version of dependencies.
![image](https://user-images.githubusercontent.com/65765369/82660668-65ef9580-9c48-11ea-87be-301115a89fc7.png)

below is where feature & stepdefination are placed.
![image](https://user-images.githubusercontent.com/65765369/82660724-83246400-9c48-11ea-9ddc-bfd5e55212c8.png)
 Can you please help me on how to make definition available to feature file.

**Comment by laeubi** [comment]
THis was improved in the 2.x line please test there and report if the issue remains
