### ISSUE TITLE
Eclipse Plugin "Cucumber" is not highlighting the Step Definition and hence Step Navigation/ Glue Code detection

### ISSUE THREAD

**Issue by bssindiana** [cucumber/cucumber-eclipse#413]
I have just installed the following Eclipse Version in my Windoes 64 desktop:
Details:
Eclipse IDE for Java Developers
Version: 2020-03 (4.15.0)
Build id: 20200313-1211

I have also installed the Cucumber Plugin:
Cucumber Eclipse Plugin 1.0.0.202005150629

Now, I have imported my existing project that has all setups configured properly and we ran and tested earlier on Intellij. When, we did same for Eclipse, it is unable to identify the Glue Code though all settings and codes existed as said. I also tried to project --> configure --> convert to Cucumber project and restarted System/ Eclipse everything. Still no luck. I tried once with @StepDefAnnotation but was also not working. I want to know, is this a Bug in Eclipse? If yes Is there a WayOut or should we wait for more stable eclipse release?

One more thing: We use the Java JDK Directory instead of JRE Directory for our runtime as we also abide by some of our organisational Security requirements

**Comment by vincent-maioranaAL** [comment]
Hello @bssindiana 

I also see similar behavior.  
- I believe that I have a repeatable test in Eclipse to show the behavior. 
- I believe that I have a klunky, temporary workaround, that works for me.
       At the very least, the repeatable test steps will show the problem reliably, and that may help the dev team.

**### Here are the details:**

Cucumber Eclipse Feature 0.0.23.201811220126
Eclipse Platform Version:                 2020-03 (4.15)
Build id:                                           I20200305-0155
Eclipse Java Development Tools	3.18.300.v20200305-0155	
Eclipse Platform	                        4.15.0.v20200305-0155
Maven Integration for Eclipse	        1.15.0.20200310-1832
Apache Maven 3.6.3                       cecedd343002696d0abb50b32b541b8a6ba2883f

**### Steps to show the problem**

Prerequisite:  Known good feature file, and known good glue code bindings. No errors, no warnings.

1. maven clean
2. maven install
3. Observe that there are no errors and no warnings from the Eclipse "Problems" Window console.
4. Observe that all functions from the Feature file are bound.
5. Add a blank line in your Feature file
6. Observe that three false errors occur.  Here's an example of one false error:
            Step '**I complete action**' does not have a matching glue code  MyFeatureFile.feature  Unmatched step

Klunky WORKAROUND

1. Save Feature file with that blank line in it
2. Right click on Warnings tab (see Figure 2) and delete Warnings
3. maven clean
4. maven install
5. Observe 
       The blank line (and potentially other edits) in the feature file is now tolerated. 
       No further warnings are presented 

Here is a sample Feature file:

# Test XX 1234 Feature Definition
             <An intentional blank line inserted>
Feature: Verify This Feature
Scenario: TestXX1234
Given items
When  I complete action
Then  I want to verify the data

**Comment by nitind** [comment]
@vincent-maioranaAL Your installation of the Cucumber plug-in seems very old. It has a datestamp from 2018.

**Comment by laeubi** [comment]
No feedback until now, please reopen with further details if this is still relevant for you.
