### ISSUE TITLE
Eclipse IDE 2020‑06 doesnt highlight yellow missing step definitions and hover link is not coming

### ISSUE THREAD

**Issue by SakthiIsaiBharathi** [cucumber/cucumber-eclipse#416]
I have installed Eclipse IDE 2020‑06 and latest cucumber plugin from snapshot URL.

- It doesnt highlight yellow color for missing step definitions.
- Hover link is not coming for feature files to navigate to respective step definitions.

**Comment by SakthiIsaiBharathi** [comment]
Can someone respond ?

**Comment by zulfikarayub** [comment]
hi even i am also facing same issue in the eclipse now , can anyone respond to it

**Comment by qvdk** [comment]
Hello, 

- Could you check your plugin version ? Do you use the latest version from the snapshot eclipse update site ?
- Do you convert you project as Cucumber project ?
- Do you build your project, or have the build automatically activated ?
- Do you have the version of the cucumber eclipse plugin 0.23 installed before ?

**Comment by zulfikarayub** [comment]
> Hello,
> 
> * Could you check your plugin version ? Do you use the latest version from the snapshot eclipse update site ?
> * Do you convert you project as Cucumber project ?
> * Do you build your project, or have the build automatically activated ?
> * Do you have the version of the cucumber eclipse plugin 0.23 installed before ?

@qvdk 

yeah i did everything which you mentioned ,but still no luck

**Comment by qvdk** [comment]
@zulfikarayub  Did you use an old version of the plugin  (ie 0.0.23) ?

In this case,  I think you have the issue #376. I describe how to clean your project setup in this [comment](https://github.com/cucumber/cucumber-eclipse/issues/376#issuecomment-534345741).

**Comment by zulfikarayub** [comment]
@qvdk  

No i was using both eclipse natural and cucumber plugin ,now i removed eclipse natural and changed the .project file as mentioned in the issue #376 

Thanks a lot it work fine now

**Comment by SakthiIsaiBharathi** [comment]
It is working as fine
