### ISSUE TITLE
error in installing  cucumber plugin

### ISSUE THREAD

**Issue by mohan19978121** [cucumber/cucumber-eclipse#419]
how do i resolve this,when am dowloading its showing this
  Cannot complete the install because one or more required items could not be found.
  Software being installed: Cucumber Eclipse 1.0.0.202007280542 (cucumber.eclipse.feature.feature.group 1.0.0.202007280542)
  Missing requirement: Cucumber Editor 1.0.0.202007280542 (cucumber.eclipse.editor 1.0.0.202007280542) requires 'bundle org.eclipse.pde.ui 3.5.0' but it could not be found
  Cannot satisfy dependency:
    From: Cucumber Eclipse 1.0.0.202007280542 (cucumber.eclipse.feature.feature.group 1.0.0.202007280542)
    To: cucumber.eclipse.editor [1.0.0.202007280542]

**Comment by laeubi** [comment]
Your Eclipse installation is not compatible with the cucumber plugin
