### ISSUE TITLE
Eclipse : Cucumber - No repository found at https://cucumber.github.io/cucumber-eclipse-update-site-snapshot/. In Eclipse

### ISSUE THREAD

**Issue by YenikeRaghuRam** [cucumber/cucumber-eclipse#427]
Eclipse : Cucumber - No repository found at https://cucumber.github.io/cucumber-eclipse-update-site-snapshot/. In Eclipse
Refer screenshots
![cucumbereclipse](https://user-images.githubusercontent.com/81166452/112117859-cee5c800-8be1-11eb-84e1-6612584c9cc4.PNG)
![CucumberEclipseUpdate](https://user-images.githubusercontent.com/81166452/112117864-d016f500-8be1-11eb-957d-072ee9671235.PNG)

**Comment by qvdk** [comment]
The update site is available.

Even if you obtain a 404 in your browser, this one will works if you use it directly in the eclipse installation wizard.

![Screenshot from 2021-04-28 13-59-37](https://user-images.githubusercontent.com/6142398/116401148-2c95b180-a82b-11eb-91dc-6d31f82f9893.png)

**Comment by YenikeRaghuRam** [comment]
I did offline installation it worked
