### ISSUE TITLE
Cucumber - Feature File - nothing shows up in editor

### ISSUE THREAD

**Issue by GDAWAR8648** [cucumber/cucumber-eclipse#430]
Cucumber eclipse not opening feature files.

using Photon Release (4.8.0)
Build ID: 20180619-1200

Eclipse Cucumber eclipse plugin version 1.0.0.202005150629
JAVA Version 11

**Comment by laeubi** [comment]
Photon is very old (Relesed in June 2018) please upgrade to a more recent version and report back if the problem persits with a more detailed error report (e.g. logs, steps to reproduce, ...)
