### ISSUE TITLE
Cucumber Eclipse Plugin: Unable to navigate to the steps implementation

### ISSUE THREAD

**Issue by NagaGanjala** [cucumber/cucumber-eclipse#432]
I have 3 maven projects in my workspace  and I'm able navigate cucumber steps implementation for 2 Projects.
But for my  3rd project steps navigation is not working .

I did maven clean, project clean ,maven update  and converted as cucumber project---but no luck
I did  >elipse.exe clean as well but still no luck.

In my Org we are using Eclipse Oxygen.

**Comment by laeubi** [comment]
You are seem to using a very old setup (Oxygen was released in June **2017**), please consider upgrading to a more recent version of eclipse and cucumber. If you still need support for your case please open a PR for the old `v0.x` release line that fixes your issue.
