### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-eclipse#433]
We've made a decision to do this on an organisation-wide basis, as we think that leaving the trunk branch as `master` could give the impression that racism isn't something we care about, which we do. See https://github.com/cucumber/common/issues/1507 for more details.

I can see there are some intricacies in the build pipeline for this project, so a simple rename of the branch would probably break things.

What support can I give you to make this happen folks?

**Comment by laeubi** [comment]
I think only here we need to rename the names as well: https://github.com/cucumber/cucumber-eclipse/blob/master/.travis.yml

**Comment by mattwynne** [comment]
OK @laeubi thanks for the feedback. Are you comfortable with me renaming the branch and making those changes to the travis manifest? I guess we can always revert if I break something...

**Comment by laeubi** [comment]
Just go ahead, if something breaks we should simply fix/adjust it no need for reverting it.

**Comment by mattwynne** [comment]
This should be done, but until #435 is complete we can't know for sure if it worked.

**Comment by mattwynne** [comment]
🤞 the release stuff in CI still works after the travis-ci.org -> travis-ci.com migration.
