### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-eclipse#435]
Travis has turned off travis-ci.org and we're all supposed to use travis-ci.com now. See [blog post](https://blog.travis-ci.com/2021-05-07-orgshutdown) and [migration instructions](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository).

I've signed up for an account on there and done my best to migrate over, but it doesn't work.

You can see an error here: https://travis-ci.com/github/cucumber/cucumber-eclipse/requests

<img width="1089" alt="Screenshot 2021-06-21 at 11 31 52 AM" src="https://user-images.githubusercontent.com/19260/122810503-49c38b00-d284-11eb-9981-696db8a975d0.png">

I wondered if it was to do with renaming `master` to `main` which I did just before migrating the repo (but after travis-ci.org had stopped building) so I wondered if that had caused confusion, but I tried renaming to back to master and it still doesn't work.

I've raised a support ticket with them.

**Comment by laeubi** [comment]
@mattwynne I think @qvdk can help here, for me it looks like there is some kind of authorization issue...

**Comment by mattwynne** [comment]
OK I think it's fixed. They had a bug letting us set our plan. We're now on their free plan. I'm still waiting to hear how suitable that is for our needs.

<img width="1087" alt="Screenshot 2021-06-23 at 10 24 01 PM" src="https://user-images.githubusercontent.com/19260/123207125-bb146100-d471-11eb-9c49-995803c5d9b1.png">
