### ISSUE TITLE
Gherkin:  .feature can't find a .step definition when it uses a parametertype on it

### ISSUE THREAD

**Issue by maioni** [cucumber/cucumber-eclipse#458]
### 👓 What did you see?

The .feature file (the gherkin) cant find the step definition when it's using a @parametertype value on it.

### Files content

.feature 
![image](https://user-images.githubusercontent.com/6604846/173433670-bf2b34a2-5a67-4c99-9c2d-30359936faf1.png)
Feature: Pages
  I want to use the menu page

  Scenario: Click on menu
    Given I click on menu

.step 
![image](https://user-images.githubusercontent.com/6604846/173433553-e972d1d3-2fec-4434-b03a-316834a2ca9d.png)
@Then("I click on {menu}")

@ParameterType("menuitema|menuitemb|menuitemc")
	public String menu(String menu) {
               if ("menuitema|menuitemb|menuitemc".contains(menu)) {
			return menu;
		}
		return "";
	}

### ✅ What did you expect to see?

The Gherkin should find the step definition, and the step definition should found the parameter type definition, this way we can CTRL + CLICK on feature to goes to the step definition.

### 📦 Which tool/library version are you using?

Eclipse + Eclipse Cucumber Plugin

### 🔬 How could we reproduce it?

1. Install  'Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)' Version: '2022-03 (4.23.0)' Build id: '20220310-1457'
2. Create a Maven Project
3. Install the 'Eclipse Cucumber Plugin' version '1.0.0.202106240526' at 'Eclipse Marketplace'
4. Convert the project to Cucumber: Open the contextual menu from your project - right click - Configure > Convert as cucumber project…
5. Clean project: Project > Clean…
6. Open the .feature file
7. Hold CTRL and click on the feature to goes to the step definition location

### 📚 Any additional context?

Parameter Type: https://cucumber.io/docs/cucumber/configuration/?sbsearch=Parameter%20type
Cucumber Expressions: Parameter type (https://cucumber.io/blog/open-source/announcing-cucumber-expressions/?sbsearch=parameter%20type)

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by laeubi** [comment]
> 3\. 'Eclipse Cucumber Plugin' version '1.0.0.202106240526'

this is only supported on the current developed 2.x version of cucumber.

**Comment by maioni** [comment]
How do I install this 2.0 version?

**Comment by maioni** [comment]
> > 3. 'Eclipse Cucumber Plugin' version '1.0.0.202106240526'
> 
> this is only supported on the current developed 2.x version of cucumber.

How install the 2.0 version?

**Comment by laeubi** [comment]
See https://github.com/cucumber/cucumber-eclipse#follow-the-latest-snapshot

**Comment by maioni** [comment]
> See https://github.com/cucumber/cucumber-eclipse#follow-the-latest-snapshot

404 > https://cucumber.github.io/cucumber-eclipse/update-site/main/

**Comment by maioni** [comment]
at Eclipse: `Help > Install New Software`
![image](https://user-images.githubusercontent.com/6604846/173682320-b2d4d5f9-7492-49f2-aaaa-0a2b214513e3.png)

`Add`
`Name`: Cucumber Eclipse Plugin 2.0
`Location`: https://cucumber.github.io/cucumber-eclipse/update-site/main/
![image](https://user-images.githubusercontent.com/6604846/173682103-c42e4ed1-106f-433a-b482-aedef908e6ce.png)
`Add`

Select `Cucumber Eclipse Plugin`, `Ansi Console`, `third party dependencies`
![image](https://user-images.githubusercontent.com/6604846/173686744-1e15a608-f2e6-410b-a5ed-d96579db42cc.png)
![image](https://user-images.githubusercontent.com/6604846/173680217-ed263814-95e2-4d47-bd45-1065c943f034.png)
`Next`

If 1.0 was installed, it will be updated to 2,0 instead:
![image](https://user-images.githubusercontent.com/6604846/173686887-461576b8-e02c-45d8-b6b2-6ac8e5ac4004.png)

`Select All`
![image](https://user-images.githubusercontent.com/6604846/173680469-95301602-c718-4fad-965e-96c0cd88c56d.png)
`Trust Selected`

![image](https://user-images.githubusercontent.com/6604846/173683631-eb159ba9-f599-4c50-84a3-09fe39bd9bd6.png)
`Restart Now`

**PROBLEM! After install 2.0, the options to convert project to cucumber is absent, and .feature files are no more associated to cucumber:** 
@laeubi 

I tried to install 2.0 after 1.0 to upgrade it, but the issue remains, and I couldn't associate .feature to cucumber properly:

Steps:
Install Cucumber Eclipse Plugin 1.0
![image](https://user-images.githubusercontent.com/6604846/173685648-a49e7269-0bd3-4595-aa8d-416769819f37.png)
Restart Eclipse

At Project, select it with right click and `Configure` > `Convert to Cucumber Project...` [OPTION ABSENT WITH 2.0, ONLY AVAILABLE WITH 1.0]
![image](https://user-images.githubusercontent.com/6604846/173686217-1136dfb2-750c-437c-81cb-a435ba680c16.png)

Select `Project` and `Clean...`  [OPTION ABSENT WITH 2.0, ONLY AVAILABLE WITH 1.0]
![image](https://user-images.githubusercontent.com/6604846/173686367-84ac98c5-47c1-4f66-ae8f-7a7043c600a0.png)

Now the feature and steps are correctly linked.  [ONLY WORKED WITH 1.0 BUT NOT COMPATIBLE WITH CUCUMBER 6/7 NEW FEATURES LIKE PARAMETER TYPE, UNABLE TO DO IT WITH 2.0 DUE TO PREVIOUSLY ISSUES]

**Comment by laeubi** [comment]
> PROBLEM! After install 2.0, the options to convert project to cucumber is absent,

2.0 do not use/require a special project type anymore. Please make sure that 1.0 is uninstalled and there are no conflicting editor assignments that take precedence.

**Comment by laeubi** [comment]
Also make sure to use a recent eclipse version.

**Comment by maioni** [comment]
@laeubi Could you give me some directions? Anything I need more to do to make 2.0 works as designed?

**Comment by maioni** [comment]
> > PROBLEM! After install 2.0, the options to convert project to cucumber is absent,
> 
> 2.0 do not use/require a special project type anymore. Please make sure that 1.0 is uninstalled and there are no conflicting editor assignments that take precedence.

Using the last version, and already installed 2.0 alone, the issue remains.

**Comment by laeubi** [comment]
There is an example project here:

https://github.com/cucumber/cucumber-eclipse/tree/main/examples/java-calculator

this requires m2eclipse to be imported and then should work at least last time i tested, if not please open an issue with the steps to reproduce the problem.

**Comment by laeubi** [comment]
> Same issue with the example project:

Sorry I don't understand, your screenshot shows the green cucumber icon for the feature and it open a gherking / cucumber editor with highligts and instant run actions so what exactly are you missing?

**Comment by maioni** [comment]
Resolution details at: https://github.com/cucumber/cucumber-eclipse/issues/459

**Comment by maioni** [comment]
After know how to install Cucumber Eclipse Plugin 2.0, and now able to test a cucumber project that uses **Parameter type**, the feature remains unable to find the step definition:

**Updating the example calculator code to support parametertype:**
Original code: https://github.com/cucumber/cucumber-eclipse/tree/main/examples/java-calculator
Updated code with parametertype implemented: [java-calculator.zip](https://github.com/cucumber/cucumber-eclipse/files/8915035/java-calculator.zip)

**Looking at these files:**
- Feature
/java-calculator/src/test/resources/io/cucumber/examples/calculator/basic_arithmetic.feature
- Step
/java-calculator/src/test/java/io/cucumber/examples/calculator/RpnCalculatorSteps.java

**And updating the step code at line 19:** 
- From:
```
    @Given("a calculator I just turned on")
    public void a_calculator_I_just_turned_on() {
        calc = new RpnCalculator();
    }
```
![image](https://user-images.githubusercontent.com/6604846/173973572-de2123bc-15e6-4077-b608-0ca53e2e3d32.png)

- To:
```
import io.cucumber.java.ParameterType;

...

@Given("a calculator I just turned {power}")
	public void a_calculator_I_just_turned_on(String power) {
		switch (power) {
		case "on":
			calc = new RpnCalculator();
			break;
		}
	}

	@ParameterType("on|off")
	public String menu(String power) {
		if ("on|off".contains(power)) {
			return power;
		}
		return "";
	}
```
![image](https://user-images.githubusercontent.com/6604846/173973356-14f7517e-1ca2-40de-9a9a-2af4fbe042a4.png)

**ISSUE**

1. When we try to HOLD LEFT CTRL key and do a mouse CLICK on line 9:
![image](https://user-images.githubusercontent.com/6604846/173974184-9da6d117-e8e7-44a4-a2ca-3edea04e37c7.png)

2. It can't find the step definition:
![image](https://user-images.githubusercontent.com/6604846/173974237-cc4e3278-8903-4b6b-9ae9-4883c7519207.png)

**Comment by laeubi** [comment]
According to your screenshot you have not saved the RnpCalculatorStep file...

Beside that its best to enhance the example (or copy it, provide an own, ...) open a PR and a separate issue.

**Comment by maioni** [comment]
New issue opened: https://github.com/cucumber/cucumber-eclipse/issues/460
