### ISSUE TITLE
After install Cucumber Plugin 2.0, the Eclipse does not associate the .feature files, does not enable the option Convert to Cucumber Project. This way the plugin can't be used.

### ISSUE THREAD

**Issue by maioni** [cucumber/cucumber-eclipse#459]
### 👓 What did you see?

After install plugin 2.0, the .feature files are not associated, and the Convert to Cucumber Project is not available. This way the .feature can't glue to step definitions.

### ✅ What did you expect to see?

After install plugin 2.0, the .feature files are associated, and the Convert to Cucumber Project is available. So the .feature will glue to step definitions correctly.

### 📦 Which tool/library version are you using?

Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components):
Version: 2022-06 (4.24.0)
Build id: 20220609-1112
![image](https://user-images.githubusercontent.com/6604846/173875443-e1a0c935-0fa3-44d5-af43-160596c462b0.png)

### 🔬 How could we reproduce it?

0. Java and Maven already installed and setup
1. Download Eclipse: https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2022-03/R/eclipse-jee-2022-03-R-win32-x86_64.zip
2. Decompress it and open Eclipse.exe
3. Update Eclipse to last version (Version: 2022-06 (4.24.0) | Build id: 20220609-1112)
4. Install and update the plugin Eclipse Web Developer Tools 3.25
5. Verify the plugin already installed: Eclipse m2e - Maven support in Eclipse IDE Latest
6. Select to Install a new Software at Eclipse Help -> Install New Software
![image](https://user-images.githubusercontent.com/6604846/173875058-76092e3e-a179-478d-8829-d1b45e003794.png)
7. Inform the name: Cucumber Eclipse Plugin 2.0
8. Inform the Location: https://cucumber.github.io/cucumber-eclipse/update-site/main/
![image](https://user-images.githubusercontent.com/6604846/173874531-e0482bc0-7d71-4341-ac31-3c1a0edab990.png)
9. Select Cucumber Eclipse Plugin: Cucumber Eclipse and third party dependencies
![image](https://user-images.githubusercontent.com/6604846/173874561-61779539-f824-45af-8de4-bc47df7417d2.png)
10. Trust: Select all and Trust Selected
![image](https://user-images.githubusercontent.com/6604846/173874604-98c147ea-5d26-44b1-b0fc-9a9f924bef8d.png)
11. After Eclipse install and restart, import the example project as a Maven Project: https://github.com/cucumber/cucumber-eclipse/tree/main/examples/java-calculator

### Actual Results

**12.** Right click on project's and select Configure -> Convert to Cucumber Project, **but the option is not available**
![image](https://user-images.githubusercontent.com/6604846/173873607-d29696d8-a702-4273-9149-9fadbc4c6803.png)
**13.** At Eclipse, goes to Windows -> Preferences -> General -> Editors -> Files Associations; and look for the .feature association; **but there's no editor associated to it**
![image](https://user-images.githubusercontent.com/6604846/173873471-6ffd8b1d-ffac-491d-b1ee-bf4a52d8bf46.png)
14. At Eclipse, goes to Project and select Clean.
![image](https://user-images.githubusercontent.com/6604846/173874937-d16a749b-1f48-4225-9d46-295c229237dd.png)
**15.** Open a .feature file and verify if it is associated to the step definitions, **but there are no glue associated**
![image](https://user-images.githubusercontent.com/6604846/173873932-99e17012-579b-4bb5-8a39-05838a0682f0.png)

### Expected Results

12. Convert to Cucumber Project available
![image](https://user-images.githubusercontent.com/6604846/173874882-6e86214f-06c9-413a-ad6e-18883d6aeefe.png)

13. .feature files are correctly associated
![image](https://user-images.githubusercontent.com/6604846/173875904-d51b52c3-b07d-4ef4-97fb-0043ac0494d3.png)

15. Feature are corrected linked/glued to the steps definitions:
![image](https://user-images.githubusercontent.com/6604846/173876459-4c8abf70-702d-40e3-94b6-0819b7a7c9e7.png)

### 📚 Any additional context?

Info: https://github.com/cucumber/cucumber-eclipse/issues/458

**Comment by laeubi** [comment]
> Convert to Cucumber Project is not available

As already mentioned, converting to cucumber project is no longer a required and not offered.

> Open a .feature file and verify if it is associated to the step definitions, **but there are no glue associated**

There is no longer an icon for glued steps, so from your screenshot everything looks fine and as expsected...

**Comment by maioni** [comment]
> > Convert to Cucumber Project is not available
> 
> As already mentioned, converting to cucumber project is no longer a required and not offered.
Thank you!
> 
> > Open a .feature file and verify if it is associated to the step definitions, **but there are no glue associated**
> 
> There is no longer an icon for glued steps, so from your screenshot everything looks fine and as expsected...
Thank you! I can see that CTRL+CLICK is working too!
![image](https://user-images.githubusercontent.com/6604846/173896459-b0289539-eb54-4fcf-af14-0daf4d1dabee.png)

**Comment by maioni** [comment]
How about the file association? Why it's not displayed into Windows > Preferences > Editors > File Association? 
![image](https://user-images.githubusercontent.com/6604846/173897203-b26899a8-8195-435c-aceb-9d3eed59779e.png)

**Comment by laeubi** [comment]
> How about the file association? Why it's not displayed into Windows > Preferences > Editors > File Association?

Cucumber-eclipse uses the "generic editor" maybe it is listed under "content types".

**Comment by maioni** [comment]
Found it! Thank you again!
![image](https://user-images.githubusercontent.com/6604846/173899552-7058237a-4f92-44d9-b31a-97a3d513d970.png)

I hope this issue could help others to make sure it's installed and working!

**Comment by maioni** [comment]
Closed!
