### ISSUE TITLE
Unable to install cucumber eclipse snapshot 1.0.0 version offline. Throwing error as missing editor requirement.

### ISSUE THREAD

**Issue by Vyom1107** [cucumber/cucumber-eclipse#462]
![B65FA927-2BEC-42BF-B92F-6AB997EA78C1](https://user-images.githubusercontent.com/109950559/180735360-6c75210d-7458-4903-9a28-34b54c2f1a5f.jpeg)

### 🔬 How could we reproduce it?

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by girijant** [comment]
@Vyom1107,
Instaed of trying with ofline intalation, I would suggest,pleae try to install from eclipe-marketplace: https://marketplace.eclipse.org/content/cucumber-eclipse-plugin/
Could you please specify the Eclipse version details?
Regards,
-Girija

**Comment by Vyom1107** [comment]
Hello Girija,
 Thank you for your revert. At present we can’t install through Market place due to firewall and proxy restrictions.

currently I am using IDE-2022-06 version

**Comment by Vyom1107** [comment]
In addition, I believe due to missing cucumber eclipse plug-in , while running test runner class as Junit, eclipse is throwing error as *Test class not found to run etc.* 

I guess this will be fixed once we successfully install cucumber plugin.

**Comment by Vyom1107** [comment]
Kindly help on above issue.

**Comment by girijant** [comment]
@Vyom1107
You may directly download & install the 2.0.0 or 1.0.0 SNAPSHOT version of plugin ofline from: https://github.com/cucumber/cucumber-eclipse/releases
![image](https://user-images.githubusercontent.com/17194046/181187820-df92deb0-c59a-42ad-8b90-da6b8ab21414.png)

**Comment by Vyom1107** [comment]
Hello Girija, thank you for revert.

will try this and let you know. Thank you!!!

**Comment by Vyom1107** [comment]
Hi Girija ,
 
Below link is showing only 1.0.0 release, there is no 2.0.0 snapshot available. Could you please check. It seems in draft status.
https://github.com/cucumber/cucumber-eclipse/releases

**Comment by laeubi** [comment]
Please see https://github.com/cucumber/cucumber-eclipse#follow-the-latest-snapshot for snapshots release, the 1.0 is most likley incompatible with recent eclipse versions
