### ISSUE TITLE
Cucumber feature file issue

### ISSUE THREAD

**Issue by GVEBhaskar** [cucumber/cucumber-eclipse#463]
Hi, 
I am new to using Cucumber. I have tried creating the feature file and executing but it was not with the below error and I have created TestRunner and StepDefinition also and executed but still I am not winning here. Please see the screen attached here so that you can understand clearly. And also please suggest the best versions of Java, Eclipse for the cucumber framework. Currently I am using Eclipse Version: 2021-12 (4.22.0) Build id: 20211202-1639 and Java version is 17.
I have been facing this problem for a couple of days. Please help in this regard.
![Screenshot (4)](https://user-images.githubusercontent.com/47274186/180907757-e2c14dd2-b325-43e8-b253-1e885a239729.png)

**Comment by laeubi** [comment]
Please try out the latest snapshot https://github.com/cucumber/cucumber-eclipse#follow-the-latest-snapshot
