### ISSUE TITLE
404 for eclipse https://cucumber.github.io/cucumber-eclipse/update-site/main/

### ISSUE THREAD

**Issue by sunil-samuel** [cucumber/cucumber-eclipse#467]
### 🔬 How could we reproduce it?

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by laeubi** [comment]
https://cucumber.github.io/cucumber-eclipse/update-site/main/ is an update-site not a web-site that delivers user content.

Simply ad the URL in the eclipse install dialog and it will work, as eclipse checks some "magic files" like https://cucumber.github.io/cucumber-eclipse/update-site/main/p2.index

**Comment by sunil-samuel** [comment]
Thank you.  I was using this URL to "Install New Software ..." via eclipse and eclipse was giving me a 404.  But it is working today.  Maybe I had something extra.  BTW, the URL, without the `p2.index` works.   Thank you again.

**Comment by laeubi** [comment]
@sunil-samuel yes the one with p2.index just was to show that there is actually content at that site (but none useful to a regular web-browser/user).

We currently use GH-pages and there might even be outages, I hope to get some time to change this to deploy to maven-central, but sadly I'm all doing this in my free time now so please be patient (or offer a funding :-) )

**Comment by sunil-samuel** [comment]
Thank you so much.  Very much appreciate you @laeubi
