### ISSUE TITLE
Comments at end of feature file are deleted on format

### ISSUE THREAD

**Issue by jadznz** [cucumber/cucumber-eclipse#47]
Comments at the end of a feature file are being deleted, I would not expect any comment text to be deleted as part of a reformat.

Reformatting the following example: 

```
Feature: feature name

  Scenario: scenario 1
    When some action
    Then some validation
    # And some more validation
```

Results in: 

```
Feature: feature name

  Scenario: scenario 1
    When some action
    Then some validation
```

**Comment by laeubi** [comment]
See https://github.com/cucumber/cucumber-eclipse/issues/442 for further work on this.
