### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-eclipse#470]
### 🤔 What's the problem you've observed?

Checks on two new PRs are failing for reasons that I think are unrelated to the change in the PR.

The error looks like this:
```
Error: [ERROR] 1 error: org/eclipse/tycho/p2maven/repository/P2RepositoryConnectorFactory has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
Error:  -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.TypeNotPresentException: Type org.eclipse.tycho.p2maven.repository.P2RepositoryConnectorFactory not present
  at ClassRealm[plugin>org.eclipse.tycho:tycho-p2-director-plugin:3.0.0, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
  while locating org.eclipse.aether.spi.connector.RepositoryConnectorFactory annotated with @com.google.inject.name.Named(value="p2")
```

### ✨ Do you have a proposal for making it better?

Investigate the cause and fix it!

### 📚 Any additional context?

https://github.com/cucumber/cucumber-eclipse/pull/468
https://github.com/cucumber/cucumber-eclipse/pull/469

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by mpkorstanje** [comment]
@mattwynne the first line in the error is a bit long, but it says we need to upgrade the Java version to 17.

**Comment by mattwynne** [comment]
Thanks @mpkorstanje, [let's see if that works](https://github.com/cucumber/cucumber-eclipse/actions/runs/3332625374/jobs/5513708902).

**Comment by mattwynne** [comment]
OK, I've updated to Java 17 but we have a new error:

```
 Error:  Failed to execute goal org.eclipse.tycho:tycho-p2-director-plugin:3.0.0:materialize-products (materialize-products) on project cucumber-eclipse: Execution materialize-products of goal org.eclipse.tycho:tycho-p2-director-plugin:3.0.0:materialize-products failed: A required class was missing while executing org.eclipse.tycho:tycho-p2-director-plugin:3.0.0:materialize-products: org/eclipse/tycho/TargetEnvironment
```

Any suggestions?

**Comment by laeubi** [comment]
Sorry I missed this issue but it is now fixed with:
- https://github.com/cucumber/cucumber-eclipse/pull/472
