### ISSUE TITLE
Unable to install Cucumber plugin from Marketplace

### ISSUE THREAD

**Issue by saptarshi-rakshit** [cucumber/cucumber-eclipse#489]
Cucumber plugin version - 1.0.0.202106240526
Eclipse version - Version: 2021-06 (4.20.0) --- Build id: 20210612-2011

Issue - installing software encountered a problem - 

Error -

An error occurred while collecting items to be installed
session context was:(profile=<user profile>, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Result of processing steps.
OK
OK
OK
Public key not found for -9147676190077153272.
OK
Result of processing steps.
OK
OK
OK
Public key not found for -9147676190077153272.
OK

**Comment by laeubi** [comment]
> Eclipse version - Version: 2021-06 (4.20.0) 

Please use a recent Eclipse version (2023-03 is the latest release)
