### ISSUE TITLE
Cannot install Cucumber Eclipse v2.0.0.202310250856 on a clean Eclipse v4.29.0

### ISSUE THREAD

**Issue by rdeltour** [cucumber/cucumber-eclipse#507]
### 👓 What did you see?

I'm trying to install the latest Cucumber for Eclipse plugin on a fresh Eclipse install (Eclipse IDE for Java), but the install fails due to missing dependencies.

### 📦 Which tool/library version are you using?

- Eclipse IDE for Java v4.29.0.
- Trying to install Cucumber Eclipse v2.0.0.202310250856
- Using update site `https://cucumber.github.io/cucumber-eclipse/update-site/main/`

### 🔬 How could we reproduce it?

1. Downloaded an installed a clean Eclipse for Java (v4.29.0)
2. Manually added `https://cucumber.github.io/cucumber-eclipse/update-site/main/` as an update site
3. Tried to install Cucumber Eclipse feature v2.0.0.202310250856
4. The install fails with the following details:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Cucumber Eclipse 2.0.0.202310250856 (cucumber.eclipse.feature.feature.group 2.0.0.202310250856)
  Missing requirement: io.cucumber:cucumber-core:6.9.1 6.9.1 (io.cucumber.cucumber-core 6.9.1) requires 'java.package; io.cucumber.cucumberexpressions [10.3.0,11.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Cucumber Eclipse 2.0.0.202310250856 (cucumber.eclipse.feature.feature.group 2.0.0.202310250856)
    To: org.eclipse.equinox.p2.iu; io.cucumber.cucumber-core [6.9.1,6.9.1]
```

### 📚 Any additional context?

On another setup I had v2.0.0.202303191054 installed. The feature included "Ansi Console" and "third party dependencies", which seem to be missing in the v202310250856 feature. 
I could update that older setup to v2.0.0.202303191054 just fine, but I am not able to install v2.0.0.202310250856 from scratch.

**Comment by benken-parasoft** [comment]
> serve the repo using a simple HTTP server

You don't need to do this.  Using "file:" URL has always worked fine.

> install the older version of the plugin, and later update to the newer one

This trick worked.  Thanks.

**Comment by jaincharu27** [comment]
I am getting similar issue. Not able to resolve it. Using https://cucumber.github.io/cucumber-eclipse/update-site/main/

Cannot complete the install because one or more required items could not be found.
  Software being installed: Cucumber Eclipse 2.0.0.202310250856 (cucumber.eclipse.feature.feature.group 2.0.0.202310250856)
  Missing requirement: Cucumber Eclipse 2.0.0.202310250856 (cucumber.eclipse.feature.feature.group 2.0.0.202310250856) requires 'org.eclipse.equinox.p2.iu; org.eclipse.unittest.ui 0.0.0' but it could not be found

**Comment by nitind** [comment]
Looks like the target definition refers explicitly to cucumber-core:6.9.1 and cucumber-expressions:11.0.0, which is explicitly incompatible.

**Comment by danibs** [comment]
I'm trying to install 2.x on:

```
Spring Tool Suite 4 
Version: 4.24.0.RELEASE
Build Id: 202407191504
```
and it is still impossibile to install

**Comment by laeubi** [comment]
I have now updated to the latest Eclipse Release and did some cleanup of dependencies making the update site self-contained with references.

I tested with a fresh [Eclipse IDE for Java Developers](https://www.eclipse.org/downloads/packages/release/2024-09/r/eclipse-ide-java-developers) and was able to install it.
