### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by ahasssan5** [cucumber/cucumber-eclipse#508]
### 🔬 How could we reproduce it?

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by kieran-ryan** [comment]
Hey @ahasssan5, is there any further information you can provide? At present we are missing information to understand how to resolve your issue. Interested to know whether any fix required 👍
