### ISSUE TITLE
Is http://cucumber.github.com/cucumber-eclipse/update-site Eclipse Update Site Down?

### ISSUE THREAD

**Issue by chinboon** [cucumber/cucumber-eclipse#52]
Hi, 

I am trying to install the cucumber-eclipse plugin using the update site http://cucumber.github.com/cucumber-eclipse/update-site as instructed here http://cukes.info/cucumber-eclipse/

However, Eclipse says:
Unable to read repository at http://cucumber.github.com/cucumber-eclipse/update-site/content.xml.
Unable to read repository at http://cucumber.github.com/cucumber-eclipse/update-site/content.xml.
org.apache.http.client.ClientProtocolException

With thanks, 
Chin Boon.
![image](https://f.cloud.github.com/assets/5987050/2107921/9038347c-8fd5-11e3-9111-b33068b7faa1.png)

**Comment by ayush880** [comment]
Follow the steps given in the below link:
http://toolsqa.com/cucumber/install-cucumber-eclipse-plugin/

**Comment by mandheer007** [comment]
> Follow the steps given in the below link:
> http://toolsqa.com/cucumber/install-cucumber-eclipse-plugin/

True.. It really worked .. !!!
