### ISSUE TITLE
Cursor position changes after autoformat

### ISSUE THREAD

**Issue by cannibalcow** [cucumber/cucumber-eclipse#56]
When running auto formating by menu or by shortcut(ctrl+shif+f) the cursor position is set at the first char on first line in feature file. 

When formating other code in eclipse eg. Java, the cursor remains in the same position after formating is done.

**Comment by laeubi** [comment]
I'll see what we can do, the "problem" on this is, that we use cucumber to format the source and replace the entire editor content with this.

**Comment by laeubi** [comment]
See https://github.com/cucumber/cucumber-eclipse/issues/442 for further work on this.
