### ISSUE TITLE
Go to StepDef from Step needs some short-cut keys and "pretty formatting"

### ISSUE THREAD

**Issue by ilanpillemer** [cucumber/cucumber-eclipse#61]
Currently the basic click through works only from the pop menu, need to enhance this by allowing control-click / F3 to do the same; and put a nice underlining over the Step when hovering over it with control-click like happens in Java Editors.

**Comment by JaspalAujla** [comment]
Earlier, this feature was available "Go to StepDef from Step under Feature file through control + click". But, it is not working now.
Must say, this short-cut is very important, otherwise it is so time consuming to find StepDef for respective Step under Feature file.

**Comment by qvdk** [comment]
Fixed by #290
