### ISSUE TITLE
Remove or change the category "Uncategorized" on the update site 

### ISSUE THREAD

**Issue by thomaseger** [cucumber/cucumber-eclipse#72]
As displayed in the screenshot below, there are two categories listed on the update site with two different versions of the feature. When choosing "Uncategorized" the installation throws an error.

The "Uncategorized" should either be removed or a meaningful name should be taken.

![install_screenshot](https://cloud.githubusercontent.com/assets/3663409/3141975/3c7c3a72-e9a3-11e3-98b0-04da72c4c50b.png)

**Comment by girijant** [comment]
@thomaseger,
Not seeign any 'Uncategorized' from Eclipse while doing plugin installation from updated-site. Hence closing this ticket.
