### ISSUE TITLE
Add shortcuts /context menu to code folding

### ISSUE THREAD

**Issue by dgarwood** [cucumber/cucumber-eclipse#76]
First, thank you very much for getting code folding working!  I can confirm it's working in Eclipse Kepler (4.3.2).

Other editors in Eclipse have a context menu available when right-clicking on a code fold icon.  Options include Expand, Collapse, Expand All and Collapse All, usually in a "Folding" sub-menu.  These can be seen in the Preferences > Keys screen.

This is apparently missing currently for cucumber-eclipse.  Tried to add these myself, but couldn't find an appropriate context for the "When" portion of the Keys setting.

**Comment by laeubi** [comment]
In 2.x the generic eclipse editor is used, please test if your issue is resolved there.
