### ISSUE TITLE
Need to be able to Debug java code [Question]

### ISSUE THREAD

**Issue by Poorman65** [cucumber/cucumber-eclipse#89]
We need to be able to set breakpoints in the Eclipse java debugger but using the cucumber runner just skips the breakpoints. There is no place to add JVM options to allow for remote debugging and I cannot find any information on how to setup debugging. Can you provide instructions on how to debug with cucumber-eclipse?

**Comment by mcattini** [comment]
Just what I was searching for.  Running my runner file using Debug As works perfectly for me.  Thank you Jakub.
