### ISSUE TITLE
How to add Run as -> Cucumber Feature menu option to different file types eg: *.yml

### ISSUE THREAD

**Issue by devisuresh** [cucumber/cucumber-eclipse#90]
Hi All,

I have customized the cucumber-eclipse plugin for our automation framework needs. For the *.feature files am seeing Run as -> Cucucmber Feature menu and its executing good. Am in need to add the same Run as -> Cucucmber Feature menu to execute different file type also *.yml.  As we have all the old testcases in this .yml file format in our project. However I have done with the changes to execute this *.yml file from plugin using run configurations But i need  Run as -> Cucucmber Feature menu option also to be displayed to .yml file. 

I want to understand how to add this run menu options for .yml and how to achieve this.

Thanks in advance.

**Comment by laeubi** [comment]
Please reopen with details if there is still demand for this.
