### ISSUE TITLE
Development environment on wiki

### ISSUE THREAD

**Issue by cannibalcow** [cucumber/cucumber-eclipse#92]
Create a small guide on the wiki how to start developing and contributing to the plugin. 
Creating project in eclipse etc.

**Comment by daveychu** [comment]
Any update on this issue? Currently tycho is complaining about the absence of a target platform, which makes the build platform dependent. It would be really helpful to know the setup of the development environment because of this.

**Comment by ilanpillemer** [comment]
Any thoughts. Originally we wanted to support Galileo and above.

**Comment by daveychu** [comment]
I suggest the following steps:
- Upgrade Tycho version to support Maven 3.1.0 (I created a pull request)
- Add a target definition file for Galileo so that people can develop in their preferred version of Eclipse
- Fix the dependency issue in GherkinLearningTest (import gherkin can't be resolved)
- And finally, adding step by step documentation on how to get a working environment

**Comment by daveychu** [comment]
Ilan, what restraints does supporting Galileo and above impose and how are they enforced? I notice two things: Maven is compiling against bundles available in the Galileo repo and compiler compliance is at java 1.6/1.7 (might as well put everything on 1.7?). Are Eclipse plug-ins by default forward compatible?

**Comment by ilanpillemer** [comment]
Hi,

It is Galileo and Java 6 as we wanted to make sure SAP Netweaver 7.3
Eclipse was supported.

**Comment by daveychu** [comment]
https://github.com/cucumber/cucumber-eclipse/pull/112 adds a target definition. I added a page to the wiki explaining how to get a working environment: https://github.com/cucumber/cucumber-eclipse/wiki/Start-contributing

**Comment by brasmusson** [comment]
I think any description of the development environment on the wiki should be linked form [CONTRIBUTING.md](https://github.com/cucumber/cucumber-eclipse/blob/master/CONTRIBUTING.md), which today seems to be the starting place for people that want to contribute.
