### ISSUE TITLE
Syntax colouring - <placeholders>  are not coloured

### ISSUE THREAD

**Issue by jakub-bochenski** [cucumber/cucumber-eclipse#93]
Nuff said I hope?

**Comment by muhqu** [comment]
> @jakub-bochenski **wrote:**
> I still think placeholders should be coloured.

Absolutely, I thought the same and took the opportunity to hack the first time on an eclipse plugin... see PR #101 for the result. :wink:

**Comment by muhqu** [comment]
`<placeholders>` are now colored :art: :shipit:

**Comment by ilanpillemer** [comment]
almost. We still need to release. Waiting to sort out getting rid of this accident license text in one file before doing that. Hopefully this week though.

**Comment by boris779** [comment]
Works for me in Version 0.0.13.201603281006
