### ISSUE TITLE
Create marketplace entry

### ISSUE THREAD

**Issue by paulvi** [cucumber/cucumber-eclipse#94]
please create marketplace entry like 
https://marketplace.eclipse.org/content/cucumber-jvm-eclipse-plugin

**Comment by brabenetz** [comment]
I searched in Eclipse Marketplace after "cucumber" and installed accidentally "Natural 0.7.6":
https://marketplace.eclipse.org/content/natural
This plugin not even supports auto-format of cucumber feature files...

please add cucumber-eclipse to the marketplace to prevent this happens again :)

create Work on cucumber-eclipse,
thanks,
Harald

**Comment by paulvi** [comment]
OK, so the issue is still on.

Now Eclipse Neon can automatically find needed plugin when file with non associated file extension is being opened.

**Comment by frankbenoit** [comment]
I just tried and could not find this plugin in marketplace from within Eclipse.

**Comment by girijant** [comment]
@paulvi, @frankbenoit, @brabenetz, @ericlemerdy, 
I am glad to announce that cucumber-eclipse plugin is now avalable in Eclipse-Market place. Please refer below URL for your plugin installation:
- https://marketplace.eclipse.org/content/cucumber-eclipse-plugin
Also refer our Eclipse-Market-Wiki page for detail information:
- https://github.com/cucumber/cucumber-eclipse/wiki/Eclipse-Market-For-Cucumber-Eclipse-Plugin
