### ISSUE TITLE
How could I install eclipse-plugin when I build my customized Eclipse

### ISSUE THREAD

**Issue by xuanzhaopeng** [cucumber/cucumber-eclipse#99]
Hi, Team

Thanks for your time, and I have a quick question, how could I find your mvn pom when I build my own customized Eclipse in mvn

Ex:
<dependency>
      <groupId>org.eclipse.zest</groupId>
      <artifactId>org.eclipse.zest.layouts</artifactId>
</dependency>

I want to know what is the Cucumber-eclipse GroupId and ArtifactId in Mvn Repository.

Thanks

**Comment by verhagen** [comment]
Hello,

It is not clear to me what you try to do.

*Case Own Eclipse Plugin*
In case you develop your own Eclipse plugins, and create a Eclipse product.
Which should also include the Cucumber Eclipse Plugin, then add it as part
of the feature (project)

*Case Extending Cucumber Eclipse Plugin*
In case you extending Cucumber Eclipse Plugin with own features, it's
probably the best to start by forking and the cloning the Cucumber Eclipse
project. As it contains the full set up.

Kind Regards, Tjeerd

**Comment by xuanzhaopeng** [comment]
Hi Tjeerd,

Thanks a lot for your quick response! Yes, I'm  in case 1.  And I will release customized Eclipse Product which already installed Cucumber-Eclipse. 

And Thanks for your information, I will add cucumber-eclipse in project file as a feature directly :)
